### ISSUE TITLE
In ecommerce, some currency symbols are hardcoded to "$"

### ISSUE THREAD

**Issue by regisb** [openedx/wg-build-test-release#135]
This issue was first reported here: https://discuss.overhang.io/t/currency-is-not-changing-on-e-commerce-course-administration/2422

There are several ecommerce templates where "$" or "USD" is hardcoded:

https://github.com/openedx/ecommerce/blob/2c2c13f541891af1c3641a542546972d54a2fd2c/ecommerce/static/templates/_course_seat.html#L6
https://github.com/openedx/ecommerce/blob/2c2c13f541891af1c3641a542546972d54a2fd2c/ecommerce/static/templates/_course_credit_seats.html#L24
https://github.com/openedx/ecommerce/blob/2c2c13f541891af1c3641a542546972d54a2fd2c/ecommerce/static/templates/honor_course_seat_form_field.html#L5
https://github.com/openedx/ecommerce/blob/2c2c13f541891af1c3641a542546972d54a2fd2c/ecommerce/static/templates/audit_course_seat_form_field.html#L5

According to the discussion above, there may also be some places in the payment MFE (with cybersource) where the "$" symbol is present.

**Comment by lxmmxl56** [comment]
I'm a new contributor and I'd like to try fixing this issue.  Do I need to be assigned or is it okay to just submit a PR once I've completed the work?

**Comment by BbrSofiane** [comment]
You can start working on it @lxmmxl56, I'll assign it to you.

**Comment by wasuregusa18** [comment]
Is this still an open issue? I would be happy to take a stab.

**Comment by mariajgrimaldi** [comment]
I left a comment in the PR: https://github.com/openedx/ecommerce/pull/3891#issuecomment-1476302718

**Comment by mariajgrimaldi** [comment]
This issue is blocked since the PR solving it has yet to be reviewed.

**Comment by mariajgrimaldi** [comment]
Update: no movement in the PR.

**Comment by mariajgrimaldi** [comment]
E-commerce repos will be archived after Sumac, so I'm not sure how we can move this forward before that happens because there is no maintainer for the e-commerce repos that can merge or review the PR. 

I'll close this issue after sumac is released.

**Comment by mariajgrimaldi** [comment]
Ecommerce was archived a few weeks ago: https://github.com/openedx-unsupported/ecommerce/pull/3891
