### ISSUE TITLE
Legacy LMS navigation issue

### ISSUE THREAD

**Issue by mrtmm** [openedx/wg-build-test-release#197]
When using the legacy LMS view in Nutmeg, navigation between units seems to have a bug.
When clicking on the "back" arrow in the bottom of the page, it won't take back to the previous unit page, but to previous subsection. If there is no previous subsection, we get a "page not found".
No errors in the logs, just a logged GET request with a 404.

Issue is present in nutmeg.1 and nutmeg.2 both.

**Comment by ZeeshanZulfiqarAli** [comment]
I am a new contributor here and would like to try fixing this one. Can you please share a bit more detail and which repo does this bug belongs to?

**Comment by jalondonot** [comment]
We're now testing the new release candidate, and this test case should be covered (https://docs.google.com/spreadsheets/d/1CX-smqwZ06eq6vyYCbNoIRZsuyGYNZoHiu_8zgmNj90).
