### ISSUE TITLE
[Olive Testing] Android plugin

### ISSUE THREAD

**Issue by cmltaWt0** [openedx/wg-build-test-release#211]
## Testings env
- Android emulator
- AVD Pixel_3a_API_33_arm64_v8a
- LMS: https://olive.demo.overhang.io
- Apk download URL: https://mobile.olive.demo.overhang.io/app.apk

## Login
State: Failed
STR:
- Click on login link
- Enter email and password
- Click login

![Screenshot 2022-10-24 at 19 48 04](https://user-images.githubusercontent.com/877401/197588393-82024b8e-8201-467f-a9bf-6555e0baf156.png)

## Registration
State: Failed
Note - user is actually created. Register the same user will give and Existent user error.
STR:
- Click on register link
- Fill Full name, Public Name, Email, Password
- Select Agreement checkbox
- Submit

<img width="431" alt="Screenshot 2022-10-24 at 20 31 44" src="https://user-images.githubusercontent.com/877401/197589292-e79f369f-9476-4c71-8108-3d574718bb22.png">

## Register page
TOS link makrup is broken.

![Screenshot 2022-10-24 at 19 46 04](https://user-images.githubusercontent.com/877401/197589781-ab3ec4e0-050a-44c3-96ef-74555212c2b8.png)

**Comment by regisb** [comment]
I can confirm that logging in is impossible. I'm getting the following logs from the server:

```
tutor_local-lms-1                        | 2022-10-24 19:11:17,763 INFO 7 [tracking] [user None] [ip 78.196.96.100] logger.py:41 - {"name": "/oauth2/access_token/", "context": {"user_id": null, "path": "/oauth2/access_token/", "course_id": "", "org_id": "", "enterprise_uuid": ""}, "username": "", "session": "", "ip": "78.196.96.100", "agent": "Dalvik/2.1.0 (Linux; U; Android 12; LE2115 Build/RKQ1.211119.001) Open edx olive Demo/io.overhang.demo.olive/3.1.4", "host": "olive.demo.overhang.io", "referer": "", "accept_language": "", "event": "{\"GET\": {}, \"POST\": {\"grant_type\": [\"password\"], \"client_id\": [\"android\"], \"username\": [\"admin\"], \"password\": \"********\"}}", "time": "2022-10-24T19:11:17.762963+00:00", "event_type": "/oauth2/access_token/", "event_source": "server", "page": null}
tutor_local-caddy-1                      | {"level":"error","ts":1666638677.780014,"logger":"http.log.access.log0","msg":"handled request","request":{"remote_addr":"78.196.96.100:39550","proto":"HTTP/2.0","method":"POST","host":"olive.demo.overhang.io","uri":"/oauth2/access_token/","tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","proto_mutual":true,"server_name":"olive.demo.overhang.io"}},"user_id":"","duration":0.033390752,"size":27,"status":401}
tutor_local-lms-1                        | [pid: 7|app: 0|req: 1485/4373] 172.18.0.8 () {44 vars in 918 bytes} [Mon Oct 24 19:11:17 2022] POST /oauth2/access_token/ => generated 27 bytes in 33 msecs (HTTP/1.1 401) 9 headers in 588 bytes (1 switches on core 0)
```

LMS is replying to POST /oauth2/access_token/ with a [401 Unauthorized](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401) error. I have no idea why.

If someone with mobile dev skills reads this, I could use a hand...

**Comment by cmltaWt0** [comment]
@regisb Custom Android build using oauth client credentials from https://olive.demo.overhang.io/oauth2/access_token/ works fine (at least Login step). So I suspect incorrect oauth client_id/token being added during the apk build step. Need to review the build process.

**Comment by cmltaWt0** [comment]
Tested on the latest deploy/build.
Login works!
<img width="427" alt="image" src="https://user-images.githubusercontent.com/877401/197863883-7edb6ef3-ee3d-4f9e-a3f5-bf6328e464cf.png">

To be continue...

**Comment by cmltaWt0** [comment]
## Additional testing for Android app

### Profile editing
Steps:
- Set Age on the Account Web page `/account` (13+ years)
- On Mobile Open profile
- Click Edit
- Change Location
- Change Spoken Language
- Add About me
- Upload Icon image
- Check changes on Profile (https://apps.olive.demo.overhang.io/profile/u/<username>) and Account `/account` page

Status: PASS

<img width="358" alt="image" src="https://user-images.githubusercontent.com/877401/200291912-9ce15ed1-d80f-4ba7-8ee2-e69d8e3c5f26.png">
<img width="360" alt="image" src="https://user-images.githubusercontent.com/877401/200291951-e2504689-ad8d-454a-b4ff-8bd45e101d98.png">
<img width="361" alt="image" src="https://user-images.githubusercontent.com/877401/200291995-cae77de6-1912-4e86-b7bd-a7afe5a4bde2.png">
<img width="1391" alt="image" src="https://user-images.githubusercontent.com/877401/200291372-4850e75b-1d68-4d54-90a9-aff271a3dc89.png">

### Enrolled course browsing
Steps:
- Enroll to a Course on the LMS Dashboard Web page
- Open Mobile app
- Login
- Check that Enrolled Course in available on the main screen

Status: FAILED

<img width="1386" alt="image" src="https://user-images.githubusercontent.com/877401/200292926-459ecb8b-91c3-4929-9d15-784dcecdc0a7.png">

**Comment by ghassanmas** [comment]
@cmltaWt0 thanks for the detailed input!.. I was going over the logs of edx-app-android to see if there might be already a fix for the last failed test and I found this openedx/edx-app-android/pull/1694 which I think is realted to the last test, if yes then we should add it to #205

**Comment by DeanJayMathew** [comment]
Awesome jobs! So @cmltaWt0 I presume we should add all these as new test cases. These will be the first new test cases added to the sheet since testing began. I endeavour to add them tomorrow.

**Comment by regisb** [comment]
Android app was upgraded to [3.2.2](https://github.com/openedx/edx-app-android/releases/tag/release%2F3.2.2) on the Olive demo server. Can you please run the failed tests again?

**Comment by arbrandes** [comment]
@cmltaWt0, have you been able to re-run the tests?

**Comment by cmltaWt0** [comment]
> @cmltaWt0, have you been able to re-run the tests?

Sure, will do today.

**Comment by cmltaWt0** [comment]
If configuration looks good I can try to backport the `My Courses screen detached fragment issue for ViewModel` fix to `olive.master` and then we can rebuild from this branch but not from a release tag.

**Comment by regisb** [comment]
Thanks for testing @cmltaWt0. I have no idea what is going on. Configuration is supposed to be ok, as I didn't change it since the last release. I also observe that the app is crashing, though I don't know why. (I don't even know how to generate a crash report on my phone...) No logs are generated on the server.

You are talking about this PR, right? https://github.com/openedx/edx-app-android/pull/1694/ It should already be present in the app, as we are running 3.2.2 which was published in October: https://github.com/openedx/edx-app-android/releases/tag/release%2F3.2.2

Any other idea?

**Comment by arbrandes** [comment]
Release janitor check: what are we doing here, if anything, for Olive.1?  We only have a couple of hours.

**Comment by regisb** [comment]
I downgraded the android plugin to 3.0.2. We'll work later to upgrade to 3.2.2.

**Comment by ghassanmas** [comment]
Following our today BTR call, there was a bug that I encournted in different context enrollment is not possible when using the APK. 

It would return 400 code, the way to resolve for that was to disable the [ProGuard](https://developer.android.com/studio/build/shrink-code) featuer. By commenting the following lines: 

https://github.com/openedx/edx-app-android/blob/11bb840580df92098717e875c7d68b6a994a9205/OpenEdXMobile/build.gradle#L501-L508

In particualr   I think this commit https://github.com/openedx/edx-app-android/commit/70909441aa085c332b08dabb29b193100ad69fb8 is probably the reason for bug.

**Comment by regisb** [comment]
I'm a terrible mobile developer and I need help with this issue, so I'll unassign myself. As an acceptance criteria, I'd like someone to open a PR on the [tutor-android](https://github.com/overhangio/tutor-android/) plugin repo to upgrade the app from 3.0.2 to 3.2.2 (or later). Users should be able to login, register and enroll in courses from the app.

**Comment by jalondonot** [comment]
@cmltaWt0, are you currently working on this? otherwise, let's mark this issue as unassigned to let people know this issue is requiring someone to work on it.

**Comment by cmltaWt0** [comment]
@jalondonot actually I don't. Was just a reported and tried to help to diagnose the issue.
Let me un-assign myself for now 👍 
Maybe later I can pick this up and try it again.

**Comment by mariajgrimaldi** [comment]
@regisb @cmltaWt0: do you folks know if this issue was resolved? If not, do you know someone we could contact to help us with this issue? I don't know anyone who is familiar with the Android app.

**Comment by regisb** [comment]
I mean, the android app is really supposed to be working in Quince, so my guess is that yes, this issue is now resolved.
