### ISSUE TITLE
[Instructor dashboard > Open responses] > Styling and layout should be improved

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/wg-build-test-release#223]
**Steps to reproduce:**

1. Go to the instructor dashboard on LMS
2. check the Open responses tab
**Expected result:**
Page styling and layout should be properly visible and styled
**Actual result:**
The text is cutting and the styling is not up to the mark.

<img width="1679" alt="instructor dashboard allignment" src="https://user-images.githubusercontent.com/55684124/199193246-2fc7b9ac-bf26-4af6-8108-5a1a252da4bc.png">

**Comment by fayyazahmed66** [comment]
label: olive testing

**Comment by arbrandes** [comment]
This might be solved if we are actually able to include [the Ora Grading MFE](https://github.com/overhangio/tutor-mfe/issues/80).

**Comment by jalondonot** [comment]
Is this issue still happening @fayyazahmed66 @DeanJayMathew?

**Comment by jalondonot** [comment]
Friendly ping, @fayyazahmed66 @DeanJayMathew :)

**Comment by fayyazahmed66** [comment]
@jalondonot  Could you please share the site's link? Unfortunately, I don't have access to the site now.

**Comment by mariajgrimaldi** [comment]
@fayyazahmed66: are you referring to the olive testing site? I don't think it is up anymore. But you could use [overhangio's demo](https://demo.openedx.overhang.io/) instance that should be using Olive.

**Comment by mariajgrimaldi** [comment]
hi there @arbrandes: do you think Ora grading is going to be included for Palm? or should we continue working on this workaround?

**Comment by arbrandes** [comment]
@mariajgrimaldi, yes, I think ORA is making it into Palm!

**Comment by mariajgrimaldi** [comment]
Unfortunately, this wasn't fixed by the ORA MFE, since it changes the grading experience but not this view in particular. So this view is ugly still 😅

**Comment by mariajgrimaldi** [comment]
I added this consideration to that ORA issue. We would appreciate it if any community member had the time to work on any of the issues mentioned there! Including this one, of course.

**Comment by mariajgrimaldi** [comment]
Fixed by: https://github.com/openedx/edx-platform/pull/33717
