### ISSUE TITLE
[TC_LEARNER_1] > Dashboard > email setting > Text is not properly visible

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/wg-build-test-release#228]
**Steps to reproduce:**

1. Go to the LMS >  dashboard 
2. Check the email setting button on the course card
**Expected result:**
The pop-up should be responsive
**Actual result:**
The pop-up isn't responsive

![Screenshot_20221025-170249](https://user-images.githubusercontent.com/55684124/201055670-7126ea7f-3cd1-4002-baf8-e5e1d118e2f5.jpg)

### PRs

- [ ] https://github.com/openedx/edx-platform/pull/31432 (master)
- [ ] https://github.com/openedx/edx-platform/pull/31433 (backport to olive)

**Comment by fayyazahmed66** [comment]
label: olive tasting

**Comment by DeanJayMathew** [comment]
label: olive testing

**Comment by mariajgrimaldi** [comment]
who should we refer this to? maybe the frontend wg? 🤔

**Comment by teyotan** [comment]
PR for this issue: https://github.com/openedx/edx-platform/pull/31433

**Comment by jalondonot** [comment]
Hi @fayyazahmed66, did you have the chance to retest this issue with the fix that was merged? if yes, could you please close this issue? thanks! :)

**Comment by fayyazahmed66** [comment]
@jalondonot  could you please give me the link to the test environment? I can't access https://olive.demo.overhang.io/dashboard

**Comment by DeanJayMathew** [comment]
@fayyazahmed66 since testing is completed, we now move back to the standard Overhang Demo platform: https://apps.demo.openedx.overhang.io/

**Comment by fayyazahmed66** [comment]
@DeanJayMathew  Same issue. I cant access it. Do I need vpn ?

**Comment by DeanJayMathew** [comment]
@jalondonot @fayyazahmed66 maybe try without the "apps" in the URL? https://demo.openedx.overhang.io/

Anyway I have checked this and it seems to be fixed now yes:

<img width="532" alt="Screen Shot 2023-01-30 at 16 03 47" src="https://user-images.githubusercontent.com/9986523/215433401-944260fc-64a4-4d1e-8640-ca24d01144a8.png">

**Comment by fayyazahmed66** [comment]
Thanks @DeanJayMathew  I am closing this ticket.
