### ISSUE TITLE
completion.enable_completion_tracking waffle flag disablement doesn't remove the progress tracking UI

### ISSUE THREAD

**Issue by throwaway-a** [openedx/wg-build-test-release#245]
In [this thread](https://discuss.openedx.org/t/course-tracking-not-working/8450/4) Braden MacDonald said that the ```completion.enable_completion_tracking``` waffle flag should disable the progress tracking UI. I expected it to disable the auto-populating green checkmarks. But that has not been my experience since I upgraded to Nutmeg. This is a regression from the Lilac behavior.

Braden also said "[Technically the Waffle flag should simply determine whether or not completion is tracked in the database](https://github.com/openedx/completion/blob/master/completion/waffle.py), not whether or not the green checks are displayed to learners, but I think the same setting was historically used for both."

I would like to request that the Lilac behavior is returned, so that I can have students track their own progress manually via completion xblocks.

**Comment by bradenmacdonald** [comment]
Just to clarify, I'm not sure if the waffle flag _should_ disable the UI. It probably makes more sense to have a separate configuration to toggle the UI (e.g. an environment variable for the Learning MFE). Because I can imagine cases where people want the data to be tracked in the backend but not shown in the frontend. But certainly it's not possible to show the UI if the data isn't there, so the "UI" toggle could default to the value of the waffle flag.

**Comment by throwaway-a** [comment]
That is a good point. I wouldn't mind having the data tracked behind the scenes so I can query it, but I don't want it showing up for students, because it tends to confuse them when they don't understand how to get a completion mark on a page.

**Comment by throwaway-a** [comment]
Does anyone know where the actual icons for the grayed out circles with checkmarks are, so that I can replace them with 1 pixel empty images? That would at least let me hack my local instance to stop showing these to students, and allow me to upgrade my server to Olive. (This UI is currently a blocking change for me. I can't confuse students like this.)

**Comment by throwaway-a** [comment]
Just to put a finer-point on it, here is what students see due to the inability to hide this UI:

![image](https://user-images.githubusercontent.com/77025740/221630712-71b09ada-9f0b-4669-9702-a8f2a2fdf815.png)

They will always see a 0% course completion on their Progress page, even if the grade is non-0%. This is obviously confusing to students, and thus is not something we can ship. We're stuck on Lilac until this is resolved.

**Comment by pdpinch** [comment]
We don’t display this UI in our current Olive deployments, but I’m not sure what setting controls it. 

Do you have a setting for SHOW_PROGRESS_BAR <https://edx.readthedocs.io/projects/edx-platform-technical/en/latest/featuretoggles.html#featuretoggle-FEATURES%5B'SHOW_PROGRESS_BAR'%5D>?

**Comment by throwaway-a** [comment]
I certainly didn't manually set that with a tutor plugin or anything like that. And I don't get any hits for either of
```
grep -r SHOW_PROGRESS_BAR /home/ubuntu/.local/share/tutor/env/
grep SHOW_PROGRESS_BAR /home/ubuntu/.local/share/tutor/config.yml
```
So is there somewhere else I should look on a tutor Nutmeg install?

**Comment by mariajgrimaldi** [comment]
@throwaway-a: I'll be testing some configurations. I'll let you know what works for me

**Comment by jalondonot** [comment]
Any update on this, @mariajgrimaldi?

**Comment by mariajgrimaldi** [comment]
The progress tab can be turned off using the learning MFE using these changes: https://github.com/openedx/wg-build-test-release/issues/278#issuecomment-1528763112
I already opened a PR and it's ready for review. Do you think that would be enough?

**Comment by mariajgrimaldi** [comment]
I opened an issue in the MFE repo: https://github.com/openedx/frontend-app-course-authoring/issues/517

**Comment by mariajgrimaldi** [comment]
The latest update is found here: https://github.com/openedx/frontend-app-course-authoring/issues/517#issuecomment-1613220082

**Comment by antoviaque** [comment]
@throwaway-a I do not know - I'm not familiar with this task, I am just trying to figure out if it has been solved for those who reported it.

**Comment by arbrandes** [comment]
A fix was merged to master in October of 2023: https://github.com/openedx/frontend-app-learning/pull/1194.  This explains why it didn't make it into quince: it probably missed the cutoff date.  For what it's worth, it'll definitely make it into Redwood.

(And if somebody opens a backport to Quince, I can try and give it some attention.)

**Comment by mariajgrimaldi** [comment]
I'll close this issue since it'll be available for redwood according to the PR merged back in October. Also, I tested it in the [community nightly sandbox](https://apps.sandbox.openedx.edly.io/learning/course/course-v1:edX+DemoX+Demo_Course/progress) and it worked as described in the PR. Thank you all!
