### ISSUE TITLE
Google Analytics 4 not supported

### ISSUE THREAD

**Issue by throwaway-a** [openedx/wg-build-test-release#246]
This has been brought up [multiple](https://discuss.openedx.org/t/google-universal-analytics-google-analytics-4-and-all-mfes/8749) [times](https://discuss.openedx.org/t/google-analytics-4-and-open-edx/3950) in the past, but I guess no one filed a ticket? Google Analytics 360 is not a viable option for small site operators. Google Universal Analytics sunsets July 1 2023. At which point all Open edX users who don't have $150k to burn will be unable to get analytics about their site usage.

The request is to add support for Google Analytics 4.

**Comment by sambapete** [comment]
The Data Working Group and the Frontend Working Group are aware of the issue. But it's a good thing to have created a ticket. Thanks.

**Comment by mariajgrimaldi** [comment]
Hello there @sambapete: do you know if there's an issue in any of those wg regarding this update?

**Comment by sambapete** [comment]
The last updates I saw were from the Data Working Group
https://openedx.atlassian.net/wiki/spaces/COMM/pages/3707699223/2023-03-22+Data+WG+Meeting+notes

I don't know if it will be ready for Palm though. Maybe @bmtcril knows more about it and the current state of

**Comment by bmtcril** [comment]
Raccoon Gang is in progress on FC-0014, with an expectation that the upgrade will be done (and I believe backported to Olive) by the end of April.

**Comment by sambapete** [comment]
It will also need to be backported to Palm which will be cut on April 11 and be released in June.

**Comment by bmtcril** [comment]
Hi all, the GA4 PRs have merged into the main branches and been backported to Palm an Olive (in anticipation of an olive.4 release)! I'm not on BTR, so I don't know if folks want to close this out or wait until things are finalized, but I think from our perspective this is complete. 

Some more details are here: https://github.com/openedx/wg-frontend/issues/148
Configuration docs are here: https://docs.openedx.org/en/latest/site_ops/how-tos/google-analytics.html
Tutor docs are coming soon.

**Comment by bmtcril** [comment]
PR for the Tutor doc update is here: https://github.com/overhangio/tutor/pull/842

**Comment by bmtcril** [comment]
And it's merged, closing this out! If issues arise please create a new issue for them. 😄
