### ISSUE TITLE
YouTube video transcript import broken

### ISSUE THREAD

**Issue by throwaway-a** [openedx/wg-build-test-release#247]
As described [here](https://discuss.openedx.org/t/how-can-i-debug-not-being-able-to-import-youtube-transcripts/6939/7) it appears that Google changed how their mechanism to download video transcripts works. As such the YouTube transcript import button hasn't worked in a long time. This has forced me (and presumably many other admins and instructors) to manually upload transcripts for hundreds of videos.

The request is to re-add support for YouTube's modified transcript download API. Either that, or to add some other way to bulk upload/sync transcripts into a course.

**Comment by mariajgrimaldi** [comment]
[This PR](https://github.com/openedx/edx-platform/pull/31412), which solves this exact issue, was merged on Dec 13th and didn't make the Olive cut. Can we consider it for a backport?

**Comment by regisb** [comment]
Thanks @mariajgrimaldi. If you do backport the change in Olive please also open a Tutor PR to cherry-pick the commit.
