### ISSUE TITLE
Palm: List of new MFEs

### ISSUE THREAD

**Issue by pdpinch** [openedx/wg-build-test-release#250]
Having a list of new MFEs will help with planning, testing, and documentation of olive. 

1. this list is still in progress
6. [frontend-app-learner-record](https://github.com/edx/frontend-app-learner-record/)

BTR requirements for an MFE to be included in the release can be found here: [Requirements for an MFE](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3561521275/Requirements+for+an+MFE)

**Comment by arbrandes** [comment]
In meeting with @pdpinch, we decided to pursue the following for Palm:

* frontend-app-ora-grading
* frontend-app-communications
* frontend-app-learner-dashboard

**Comment by jmakowski1123** [comment]
@pdpinch @arbrandes The new problem editor went live on edX.org. I believe we should we able to include this in Palm as well since it's part of the Course Authoring MFE? Product info and how to enable here: https://openedx.atlassian.net/wiki/spaces/OEPM/blog/2023/04/07/3724312593/New+Visual+Problem+Editor

**Comment by jmakowski1123** [comment]
> In meeting with @pdpinch, we decided to pursue the following for Palm:
> 
> * frontend-app-ora-grading
> * frontend-app-communications
> * frontend-app-learner-dashboard

@pdpinch @arbrandes I believe this is the product info for the new Learner Dashboard, though could @ProductRyan confirm?

And here is additional product info on the new ORA grading experience: https://openedx.atlassian.net/wiki/spaces/OEPM/blog/2022/10/21/3560898586/2U+The+New+ORAs+Grading+Experience

**Comment by pdpinch** [comment]
@jmakowski1123 regarding the problem editor, my understanding is that, as a part of the Course Authoring MFE, it is already included in Palm. I'll include it in the release notes, and we should add it to the testing plan as well.

**Comment by arbrandes** [comment]
For the record, after a meeting last week the following was decided:

* ORA Grading: still pending [this PR](https://github.com/openedx/frontend-app-ora-grading/pull/146) (on Adolfo’s court)
* Communications: needs a community maintainer and proper review.
* Learner Dashboard: will be offered as “experimental”.  The current maintaining team at 2U has agreed to review PRs that address bugs and other changes that make it work with Tutor, but not new features: this makes it difficult to include it officially.  It is suggested that a tutor-contrib-learner-dashboard plugin be created in the openedx org.

**Comment by arbrandes** [comment]
Status update: ORA Grading and Communications are in!

**Comment by arbrandes** [comment]
Status update: ORA Grading and Comms are in.  Learner Dashboard now has [a draft plugin](https://github.com/openedx/openedx-tutor-plugins/pull/4) (that actually works), but [the PR that fixes up the dashboard itself](https://github.com/openedx/frontend-app-learner-dashboard/pull/136) is still pending.

**Comment by arbrandes** [comment]
Status update:  Learner Dashboard [has a plugin](https://github.com/openedx/openedx-tutor-plugins/tree/main/plugins/tutor-contrib-learner-dashboard-mfe#learner-dashboard-mfe-plugin-for-tutor), and the upstream fix is also in.  Looks like we're done here!
