### ISSUE TITLE
Django 3.2.18 security patch

### ISSUE THREAD

**Issue by jalondonot** [openedx/wg-build-test-release#251]
Django 3.2.18 will be released Feb 14: Django will be issuing a security fix: https://groups.google.com/g/django-announce/c/H1PcSV_u1hM/m/II_eHOmUEQAJ

**Comment by jfavellar90** [comment]
I was checking and @mtyaka applied the last 2 Django patches (the last one is [here](https://github.com/openedx/edx-platform/pull/31723) ). Could you apply the patch for 3.2.18? If not, @mariajgrimaldi could you come to the rescue? Just let me know guys if any of you take it over :)

**Comment by mtyaka** [comment]
I'll do it @jfavellar90, thanks for the ping.

**Comment by mtyaka** [comment]
This is complete. I used Ned's scripts from https://discuss.openedx.org/t/django-2-2-19-security-update/4305 to prepare and push the update to all affected Olive repositories.
