### ISSUE TITLE
Backport for Olive.3 

### ISSUE THREAD

**Issue by ghassanmas** [openedx/wg-build-test-release#253]
We might need to backport PRs before the release of olive.3 here are the candidates s
- [ ] openedx/cs_comments_service/pull/409 
- [ ] Update langauge for MFEs partiuclary auth/German 
   - [x] Update frontend-app-auth lang openedx/frontend-app-authn/pull/761 
   - [ ] Update course authroing openedx/frontend-app-course-authoring/pull/454 
- [x] https://github.com/openedx/edx-platform/pull/31862 by @mariajgrimaldi closes #247 
- [ ] MFE payment fix  openedx/frontend-app-payment/pull/716 by @Lunyachek

Ref: Slack thread https://openedx.slack.com/archives/C049JQZFR5E/p1677584618177399

**Comment by mariajgrimaldi** [comment]
Can we include this backport as well? https://github.com/openedx/edx-platform/pull/31862, that issue also solves https://github.com/openedx/wg-build-test-release/issues/247

**Comment by ghassanmas** [comment]
@mariajgrimaldi added I also added in the assigned given you are already assigned to the one of the PRs

**Comment by mariajgrimaldi** [comment]
@ghassanmas: great! thanks

**Comment by ghassanmas** [comment]
Closing in favour of #261
