### ISSUE TITLE
Features flags and Settings changes between olive to palm

### ISSUE THREAD

**Issue by ghassanmas** [openedx/wg-build-test-release#260]
Just like #204 here are the changes of settings/featuers between olive to palm. 

## Deleted Features/Toggles
- block_structure.raise_error_when_not_found [ref](https://github.com/openedx/edx-platform/blob/db111c05f6d8172c5629e9d723844565ac657476/openedx/core/djangoapps/content/block_structure/config/__init__.py#L51)
- credentials.use_learner_record_mfe [ref](https://github.com/openedx/edx-platform/blob/db111c05f6d8172c5629e9d723844565ac657476/openedx/core/djangoapps/credentials/config.py#L10)

## New Features/Toggles
 - `DISABLE_JWT_FOR_MOBILE`  [ref](https://github.com/openedx/edx-platform/blob/8e6e2997151e010276f5d76db7269c1f1d2af702/openedx/core/djangoapps/oauth_dispatch/toggles.py#L10) 
 - `DISABLE_ADVANCED_SETTINGS` [ref](https://github.com/openedx/edx-platform/blob/8e6e2997151e010276f5d76db7269c1f1d2af702/cms/envs/common.py#L520) 
 - `DISABLE_ALLOWED_ENROLLMENT_IF_ENROLLMENT_CLOSED` [ref](https://github.com/openedx/edx-platform/blob/8e6e2997151e010276f5d76db7269c1f1d2af702/lms/envs/common.py#L1022) 
 - `ENABLE_SEND_XBLOCK_EVENTS_OVER_BUS` [ref](https://github.com/openedx/edx-platform/blob/8e6e2997151e010276f5d76db7269c1f1d2af702/cms/envs/devstack.py#L303) 
 - `JWT_AUTH_FORCE_CREATE_ASYMMETRIC` [ref](https://github.com/openedx/edx-platform/blob/8e6e2997151e010276f5d76db7269c1f1d2af702/openedx/core/djangoapps/oauth_dispatch/jwt.py#L198) 
 - `instructor_task.use_on_disk_grade_reporting` [ref](https://github.com/openedx/edx-platform/blob/8e6e2997151e010276f5d76db7269c1f1d2af702/lms/djangoapps/instructor_task/config/waffle.py#L27) 
 - `learner_home_mfe.enabled` [ref](https://github.com/openedx/edx-platform/blob/8e6e2997151e010276f5d76db7269c1f1d2af702/lms/djangoapps/learner_home/waffle.py#L13) 
 - `learner_home_mfe.enable_learner_home_amplitude_recommendations`  [ref](https://github.com/openedx/edx-platform/blob/8e6e2997151e010276f5d76db7269c1f1d2af702/lms/djangoapps/learner_home/recommendations/waffle.py#L10) 
 - `learner_recommendations.enable_course_about_page_recommendations` [ref](https://github.com/openedx/edx-platform/blob/8e6e2997151e010276f5d76db7269c1f1d2af702/lms/djangoapps/learner_recommendations/toggles.py#L10) 
 - `learner_recommendations.enable_dashboard_recommendations` [ref](https://github.com/openedx/edx-platform/blob/8e6e2997151e010276f5d76db7269c1f1d2af702/lms/djangoapps/learner_recommendations/toggles.py#L24) 
 - `student.enable_enrollment_confirmation_email` [ref](https://github.com/openedx/edx-platform/blob/8e6e2997151e010276f5d76db7269c1f1d2af702/common/djangoapps/student/toggles.py#L61) 
 - `student.enable_fallback_recommendations`  [ref](https://github.com/openedx/edx-platform/blob/8e6e2997151e010276f5d76db7269c1f1d2af702/common/djangoapps/student/toggles.py#L26) 
 - `third_party_auth.apple_user_migration`  [ref](https://github.com/openedx/edx-platform/blob/8e6e2997151e010276f5d76db7269c1f1d2af702/common/djangoapps/third_party_auth/toggles.py#L9) 
 - `video_config.public_video_share`  [ref](https://github.com/openedx/edx-platform/blob/8e6e2997151e010276f5d76db7269c1f1d2af702/openedx/core/djangoapps/video_config/toggles.py#L8) 
 
 ## Deleted Settings 
 - `LEARNER_RECORD_MFE_URL` [ref](https://github.com/openedx/edx-platform/blob/db111c05f6d8172c5629e9d723844565ac657476/lms/envs/common.py#L4894)
 - `XBLOCK_SELECT_FUNCTION` [ref](https://github.com/openedx/edx-platform/blob/db111c05f6d8172c5629e9d723844565ac657476/lms/envs/common.py#L1531)
 
 ## New Settings
 - `SECURITY_PAGE_URL`  [ref](https://github.com/openedx/edx-platform/blob/8e6e2997151e010276f5d76db7269c1f1d2af702/lms/envs/common.py#L3355)

**Comment by kdmccormick** [comment]
@ghassanmas There be an issue with your data, `XBLOCK_SELECT_FUNCTION` was defined on olive.master but is removed in palm.master.

**Comment by ghassanmas** [comment]
@kdmccormick good catch, my fault I think I did the `git diff` in the wrong order, now it should be correct. Can you confirm my latest edit

**Comment by kdmccormick** [comment]
Looks good, thanks!

**Comment by jalondonot** [comment]
@pdpinch. Tagging you in case this information is valuable for the release notes.

**Comment by pdpinch** [comment]
I've added these to the release notes, https://github.com/openedx/docs.openedx.org/pull/321

@ghassanmas do you know why `course_experience.relative_dates_disable_reset` didn't show up on your list?

https://edx.readthedocs.io/projects/edx-platform-technical/en/latest/featuretoggles.html#featuretoggle-course_experience.relative_dates_disable_reset

**Comment by ghassanmas** [comment]
@pdpinch checking now, this is beacuse it was added to edx-platform after branch cut date, hence 

- openedx/edx-platform/pull/32148  

was merged **after release cut date**, so I guess probably we need to backport the above PR, given it doesn't exists on palm.master https://github.com/openedx/edx-platform/blob/open-release/palm.master/openedx/features/course_experience/__init__.py

**Comment by pdpinch** [comment]
Oops. For some reason, I thought that was in Palm, but it's not. I don't think we need to backport unless someone asks for it.

**Comment by pdpinch** [comment]
These have all been added to the release notes PR at https://github.com/openedx/docs.openedx.org/pull/321
