### ISSUE TITLE
TC_LEARNER_8: Registration email was not received

### ISSUE THREAD

**Issue by DeanJayMathew** [openedx/wg-build-test-release#264]
The account registration email was not received.

**Comment by jswope00** [comment]
FWIW, I was able to get this today at a mailinator address. Also got a password reset email on my normal email account, though it went to spam as expected. Perhaps something changed in last two days. https://prnt.sc/_WCrH8arZjx2

**Comment by sambapete** [comment]
Still doesn't work for me. It didn't for for Olive either. Like @regisb previously said it is a very basic SMTP server behind the demo server. Some receiving SMTP servers may require options that are not configured on the demo server like DKIM records or SPF records.

**Comment by sambapete** [comment]
I was able to receive the email as spam on a Zoho email account but not in my @gmail.com or @umontreal.ca accounts.

I would suggest we mark it as passed. Your call @DeanJayMathew

**Comment by sambapete** [comment]
Finally received the activation and reset emails on my @umontreal.ca email address. Office 365 considered it High Trust Phishing
