### ISSUE TITLE
TC_LEARNER_17: Unable to configure course email preferences

### ISSUE THREAD

**Issue by DeanJayMathew** [openedx/wg-build-test-release#265]
Steps to replicate:

Go to https://palm.demo.overhang.io/dashboard and click the gear icon next to any course to view two options, namely to unenrol from the course and to configure email preferences for the course.

Expected result:
I expected to see two options, firstly an option to unenrol from the course, and secondly an option to configure email preferences for the course. 

Actual result:

I only see the former option (unenrol) and not the latter (email preferences, there used to be a button for this right?):

<img width="990" alt="Screen Shot 2023-04-20 at 14 29 08" src="https://user-images.githubusercontent.com/9986523/233292468-f29f2093-7712-4917-b9a2-1707fd98df8e.png">

**Comment by DeanJayMathew** [comment]
label: palm testing

**Comment by jswope00** [comment]
I activated the option by enabling the bulk email flag in admin panel 
![image](https://user-images.githubusercontent.com/1486185/233789760-3fc6409b-15ef-42bc-941e-084b162c3da9.png)

Now the option exists on the learner dashboard. 
![image](https://user-images.githubusercontent.com/1486185/233789774-6b510365-db39-4e4f-9e27-9f023faeb92f.png)

**Comment by jswope00** [comment]
I added a note to the testing sheet to clarify the requirement to enable this flag before this item can be tested.

**Comment by mariajgrimaldi** [comment]
Thanks @jswope00! Could you let me know if you managed to configure your email preferences?

**Comment by DeanJayMathew** [comment]
Thanks, @jswope00 well played. Cheers for adding the instructions to the test sheet.

@mariajgrimaldi I created a learner account for myself and tried to send en email, but since the platform email service is not fully configured, it's tough to test if the email settings actually works or not. Perhaps someone with a Zoho email address could check, since I believe platforms email are in fact delivering to Zoho based on comments in https://github.com/openedx/wg-build-test-release/issues/264.

**Comment by jswope00** [comment]
@mariajgrimaldi yes, I was able to unsubscribe from emails and confirm that address wasn't receiving bulk emails. This can be closed now, IMO.
