### ISSUE TITLE
Account link in User dropdown is failing on the Course pages

### ISSUE THREAD

**Issue by jswope00** [openedx/wg-build-test-release#268]
From all tabs in a course, the 'Account' link in the User dropdown appears to be linking to itself, and so the link is not correctly directing the user to the Account page: 
https://prnt.sc/_jcsuHqKwMed

**Comment by ghassanmas** [comment]
I think I have also noticed that in MFEs, and it's probably something related to the header componenet. I will investage further as I think this probably affect few MFEs.

**Comment by ghassanmas** [comment]
I think newer version of account takes the url from the settings thus tutor-mfe shall send it. I am looking into it

**Comment by mariajgrimaldi** [comment]
@ghassanmas: can we close this issue? Thank you so much for the fix!

**Comment by ghassanmas** [comment]
No worries, yes I think it's resoveld now
