### ISSUE TITLE
Notes needs to be enabled?

### ISSUE THREAD

**Issue by jswope00** [openedx/wg-build-test-release#271]
I am unable to enable Notes from Studio either via Advanced Settings or the new Pages & Resources MFE. I think the plugin might still need to be configured? https://github.com/overhangio/tutor-notes

**Comment by mariajgrimaldi** [comment]
Notes hasn't been enabled on the test server yet! Also I think it doesn't have palm support yet either 🤔.

**Comment by mariajgrimaldi** [comment]
I'll give palm support to the tutor-notes plugin :)

**Comment by DeanJayMathew** [comment]
Thank you @mariajgrimaldi what a champ!

**Comment by mariajgrimaldi** [comment]
@jfavellar90 is already working on the update :)! Thank you so much!

**Comment by mariajgrimaldi** [comment]
It seems to be working:
![image](https://github.com/openedx/wg-build-test-release/assets/64440265/206d9f1a-ee40-4403-a6b2-49852000fdac)
![image](https://github.com/openedx/wg-build-test-release/assets/64440265/f40e6330-eab0-4478-91d1-c99ef666bc65)

**Comment by mariajgrimaldi** [comment]
Since notes it's already enabled, I'll be closing this issue. If you folks find any other problem with notes, please open a new GH issue :)

**Comment by DeanJayMathew** [comment]
Now that this is closed, it should also be updated on the Test Sheet. I have gone ahead and done so. Woohoo thanks to you all!
