### ISSUE TITLE
"Advanced Settings" Menu item missing on some pages

### ISSUE THREAD

**Issue by jswope00** [openedx/wg-build-test-release#272]
Perhaps this is a well-intentioned feature? 

But it appears that "Advanced Settings" is now only available from the Studio Course Outline page. It is not available on any other studio pages: 
![image](https://user-images.githubusercontent.com/1486185/234436013-6a1a0e86-a4f0-4b90-87e5-9806fe97db14.png)

![image](https://user-images.githubusercontent.com/1486185/234436059-32e7d6b9-32a0-4875-ae0c-454922221c15.png)

**Comment by jalondonot** [comment]
@pdpinch could you please add the open PR that should fix this? thanks :)

**Comment by Agrendalath** [comment]
@0x29a, @farhaanbukhsh, we should backport https://github.com/openedx/edx-platform/pull/32097 to the Palm branch to fix this.

**Comment by 0x29a** [comment]
@Agrendalath, thanks for noticing this issue. I'll prepare the backport PR soon.

**Comment by 0x29a** [comment]
@jswope00, @Agrendalath, @pdpinch, here is the backport PR: https://github.com/openedx/edx-platform/pull/32309.

**Comment by Agrendalath** [comment]
@0x29a, merged; thanks! We can close this.
