### ISSUE TITLE
Honor Certificate does not display signature Images

### ISSUE THREAD

**Issue by jswope00** [openedx/wg-build-test-release#273]
If there is a good reason for this, feel free to close it. But the certificate has a CSS rule that hides the signatures if it is an honor-mode certificate. I think most Open edX instances use honor mode for their certificates and want to show the signatures. Can this rule be removed? 

![image](https://user-images.githubusercontent.com/1486185/234439023-825d51cf-1f31-4e6d-ae6e-b3340dbb8e4a.png)

**Comment by mariajgrimaldi** [comment]
I reported this a while ago: https://github.com/openedx/wg-build-test-release/issues/177#issuecomment-1124246022
