### ISSUE TITLE
Certificate signatures stack on print mode and extend to two pages

### ISSUE THREAD

**Issue by jswope00** [openedx/wg-build-test-release#274]
When printing the certificate, the signatures go from displaying on the same row in the web view to displaying in a stacked view on the print view. This leads to the print being larger than a standard 8.5x11 page. 

![image](https://user-images.githubusercontent.com/1486185/234439455-e0680ec6-fd61-45f0-9cd1-43cc1ebbd16e.png)

![image](https://user-images.githubusercontent.com/1486185/234439690-1005490d-8f6f-418d-8bb7-f96885b90350.png)

**Comment by pdpinch** [comment]
Should the release notes include this as a "known issue"? If so please propose some text on the release notes PR at https://github.com/openedx/docs.openedx.org/pull/321

**Comment by BetoFandino** [comment]
I have been working on this.

**Comment by BetoFandino** [comment]
assign me

**Comment by fayyazahmed66** [comment]
@mariajgrimaldi  Actual issue is fixed but now we need some more spaces between signatures.

<img width="1678" alt="signatury" src="https://github.com/openedx/wg-build-test-release/assets/55684124/368e93b1-f97f-4be2-b4ae-34e66e17adf2">

**Comment by mariajgrimaldi** [comment]
I'll close this since the actual issue was solved. I also opened a new one for the improvement left.
