### ISSUE TITLE
[BUG] Video uploads broken link

### ISSUE THREAD

**Issue by cmltaWt0** [openedx/wg-build-test-release#275]
MFE: https://github.com/openedx/frontend-app-course-authoring

Dropdown link `Content > Video Uploads` in Pages&Uploads leads to 404.

<img width="811" alt="image" src="https://user-images.githubusercontent.com/877401/234626372-e97ee67b-98e4-42c3-b3bd-5ff1ec110c5d.png">
<img width="694" alt="image" src="https://user-images.githubusercontent.com/877401/234626441-bf51583b-8b0f-42fb-8c40-523fd02f6cd9.png">

Other links:
- https://discuss.openedx.org/t/the-issue-with-video-uploads-button-in-course-authoring-mfe/10221

**Comment by DeanJayMathew** [comment]
@jalondonot @mariajgrimaldi @cmltaWt0 

Has anyone been able to find the reason there is an error for this? If we can't find the error it might be best to remove that link for Palm?

**Comment by cmltaWt0** [comment]
I've added the link to discuss post with some root cause analysis.
