### ISSUE TITLE
Discussion errors in the demo course

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-build-test-release#276]
### Issue

Many units in the demo course show an overlay saying "The discussion could not be loaded.":

![image](https://user-images.githubusercontent.com/3628148/234913548-26fd1526-538a-433d-a2f0-6b2bf0a8b446.png)

Clicking OK removes the overlay and lets the user continue as normal, but this happens in many units and is annoying.

### Notes

* I did confirm this on the [demo course in the Palm instance](https://apps.palm.demo.overhang.io/learning/course/course-v1:edX+DemoX+Demo_Course). However, it has been the case for a while, at least back to Nutmeg and maybe earlier.
* This does **not** happen in the [_test_ course in the Palm instance](https://apps.palm.demo.overhang.io/learning/course/course-v1:TestX+Course+1/home). I'm not sure why it's different.
* @bmtcril tried a couple things on his local instance:
  * He tried disabling discussions via Django admin. That didn't fix the error.
  * He enabled the tutor-forum plugin and restarted. This **did** resolved the error. However, since tutor-forum isn't enabled by default, we need a way of avoiding the error without enabling the forums.
* @feanil thinks that disabling the `ENABLE_DISCUSSION_SERVICE` toggle when tutor-forum is not enabled might resolve the issue.

**Comment by jalondonot** [comment]
Hi, @kdmccormick! Have you had a chance to continue working on this? :)

**Comment by mariajgrimaldi** [comment]
@DmytroAlipov: thank you so much! I'll review the PR against the master branch as soon as possible.

**Comment by mariajgrimaldi** [comment]
The fix contributed by @DmytroAlipov was already merged to the `palm.master` branch. Thank you. I'll be closing this then! If you have any of you folks have an objection, you can reopen this issue explaining why ;)

**Comment by kdmccormick** [comment]
Thank you Dmytro and Maria!
