### ISSUE TITLE
[TC_AUTHOR_9] STUDIO: MAINTENANCE > Announcements are not appearing on learner dashboard

### ISSUE THREAD

**Issue by mariajgrimaldi** [openedx/wg-build-test-release#280]
## Description
Announcements are not appearing after creating it on the maintenance Studio menu.

## How to reproduce

1. Enter studio with a global staff account
2. Go to the maintenance dashboard: right menu > maintenance
3. Enter Announcements
4. Create an announcement
5. Go to the learner dashboard as a student
6. The announcement should appear on the right

This is how it's currently behaving:
![image](https://user-images.githubusercontent.com/64440265/236507102-b4ff5686-4107-4a5b-babc-e26ffa6beea3.png)
![image](https://user-images.githubusercontent.com/64440265/236506990-dd081766-4027-4bc8-9968-41d4d1348195.png)

Am I missing something here? is this how it's supposed to behave?

**Comment by DeanJayMathew** [comment]
Oh I thought Announcements should show up inside the course, but now I see that is the Notifications:

<img width="1440" alt="Screen Shot 2023-05-17 at 12 42 38" src="https://github.com/openedx/wg-build-test-release/assets/9986523/06432511-b42a-402d-9b4c-17459d985efe">

Both these features don't work. 

We can either try find our how to fix these, or we can have them removed from the platform. I prefer option 1!

Maybe OpenCraft or RaccoonGang or Edly know how to resolve these.

**Comment by mariajgrimaldi** [comment]
Thanks for checking that out! @DeanJayMathew: should we open a new issue for notifications?

**Comment by DeanJayMathew** [comment]
@mariajgrimaldi yes indeed let's open a new issue. I've added it here: https://github.com/openedx/wg-build-test-release/issues/293

**Comment by pdpinch** [comment]
Should the release notes include this as a "known issue"? If so please propose some text on the release notes PR at https://github.com/openedx/docs.openedx.org/pull/321

**Comment by jacobpradels** [comment]
Was this feature disabled?  I don't even see the panel where announcements would appear anymore when trying to reproduce.

**Comment by mariajgrimaldi** [comment]
Thank you all for looking into this! I completely missed the configuration back then, and it's confusing as well since the UI is always available, but it doesn't work without the flag. I tested locally using the **legacy** learner dashboard, and it's working correctly. It looks like it's not supported in the learner dashboard MFE.

Thank you again!
