### ISSUE TITLE
Django 3.2.19 security patch (Olive)

### ISSUE THREAD

**Issue by mtyaka** [openedx/wg-build-test-release#282]
Apply the [3.2.19 security patch](https://www.djangoproject.com/weblog/2023/may/03/security-releases/) to Olive ~~and Palm~~ branches.

**Comment by mariajgrimaldi** [comment]
Hi there! can you link both PR(s) once you have them? Thanks!

**Comment by mtyaka** [comment]
@mariajgrimaldi These are the PRs for Olive:

- https://github.com/openedx/edx-platform/pull/32265
- https://github.com/openedx/ecommerce/pull/3974
- https://github.com/openedx/enterprise-catalog/pull/602
- https://github.com/openedx/blockstore/pull/253
- https://github.com/openedx/edx-analytics-data-api/pull/622
- https://github.com/openedx/edx-analytics-dashboard/pull/1454
- https://github.com/openedx/xqueue/pull/890
- https://github.com/openedx/ecommerce-worker/pull/200
- https://github.com/openedx/enterprise-access/pull/173
- https://github.com/openedx/edx-notes-api/pull/333
- https://github.com/openedx/license-manager/pull/492
- https://github.com/openedx/course-discovery/pull/3949
- https://github.com/openedx/credentials/pull/2010

I'll create the PRs for Palm tomorrow.
