### ISSUE TITLE
[ Studio > Author > TC_AUTHOR_54] H5P Xblock is not appearing in advance blocks

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/wg-build-test-release#284]
I have executed TC_AUTHOR_54 and concluded that after adding H5P Xblock in advance settings of the studio, I can't find H5P Xblock under advance Xblocks lists.

**Steps to reproduce:**

1. Go to https://studio.palm.demo.overhang.io/course/course-v1:edX+DemoX+Demo_Course
2. Click on the settings drop-down and go to advanced settings
3. Add "h5pxblock" in the advance settings list and click on the save button
4. Now add a new unit in the same course and click on advance Xblocks

**Expected result:**
h5pxblock Should be there.

**Actual result:**
h5pxblock isn't visible.

<img width="1679" alt="h5p1" src="https://github.com/openedx/wg-build-test-release/assets/55684124/f0be7cd5-39c2-4a8b-b5b7-519e29824407">

<img width="1673" alt="hf52" src="https://github.com/openedx/wg-build-test-release/assets/55684124/fc0d0358-fe2e-48a2-965f-d0ce99db381c">

**Comment by fayyazahmed66** [comment]
label: palm testing

**Comment by fayyazahmed66** [comment]
@sambapete Who can add it for testing? I think its batter if we could add a xblocks mentioned in test cases.

**Comment by DeanJayMathew** [comment]
@fayyazahmed66 @sambapete

We can close this issue I think as this feature is not supported. For Olive, the team at AulasNeo kindly tested it. I believe the Palm (and beyond) test cases should reflect only the supported features. Should we deprecate this test case and close this issue?

**Comment by sambapete** [comment]
I agree with you @DeanJayMathew

**Comment by fayyazahmed66** [comment]
Sure @DeanJayMathew . I am closing it.
