### ISSUE TITLE
[ Studio > Author > TC_AUTHOR_64] freetextresponse Xblock is not appearing in advance blocks

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/wg-build-test-release#285]
I have executed TC_AUTHOR_64 and concluded that after adding freetextresponse Xblock in advance settings of the studio, I can't find freetextresponse Xblock under advance Xblocks lists.

**Steps to reproduce:**

1. Go to https://studio.palm.demo.overhang.io/course/course-v1:edX+DemoX+Demo_Course
2. Click on the settings drop-down and go to advanced settings
3. Add "freetextresponse" in the advance settings list and click on the save button
4. Now add a new unit in the same course and click on advance Xblocks

**Expected result:**
freetextresponse Should be there.

**Actual result:**
freetextresponse isn't visible.
<img width="1679" alt="freetext" src="https://github.com/openedx/wg-build-test-release/assets/55684124/1bbfa422-d83d-49a5-a4fb-6dfa2f3d8e2b">

**Comment by sambapete** [comment]
I don't believe freetextresponse has been added on the Palm Test Server. It is not a default XBlock.

**Comment by fayyazahmed66** [comment]
@sambapete  Who can add it for testing ?

**Comment by DeanJayMathew** [comment]
@fayyazahmed66 @sambapete 

We can remove Test Cases that cover non-standard features. As this XBlock is a 3rd party XBlock, it may not even be working if someone does have the time to install it on the test instance. 

We can close this issue I think.

**Comment by sambapete** [comment]
I agree with you @DeanJayMathew

**Comment by fayyazahmed66** [comment]
Got it. Thanks for the clarification. I am closing it.
