### ISSUE TITLE
[ Studio > Author > TC_AUTHOR_74 ] prerequisite Xblock is not appearing in advance blocks

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/wg-build-test-release#286]
I have executed TC_AUTHOR_74 and concluded that after adding prerequisite Xblock in advance settings of the studio, I can't find prerequisite Xblock under advance Xblocks lists.

Steps to reproduce:

Go to https://studio.palm.demo.overhang.io/course/course-v1:edX+DemoX+Demo_Course
Click on the settings drop-down and go to advanced settings
Add "prerequisite" in the advance settings list and click on the save button
Now add a new unit in the same course and click on advance Xblocks
Expected result:
prerequisite Should be there.

Actual result:
prerequisite isn't visible.

<img width="1679" alt="prereq" src="https://github.com/openedx/wg-build-test-release/assets/55684124/42e97407-4bda-4b26-878c-3a0bfd04d978">

**Comment by sambapete** [comment]
It is not supposed to be an Advance Module.

<img width="1002" alt="Capture d’écran, le 2023-05-15 à 12 37 14" src="https://github.com/openedx/wg-build-test-release/assets/8906669/cb4da9d0-390f-4c5f-b7e8-eeefc5a8de67">

I believe the test refers to the prerequite advanced settings as per
https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/latest/developing_course/controlling_content_visibility.html#prerequisite-course-subsections

**Comment by fayyazahmed66** [comment]
@sambapete 
I also thought the same but then I check the location in the test case and it was referred to Xlocks. Let me retest and update the ticket.

**Comment by fayyazahmed66** [comment]
@sambapete  is right. I am closing this ticket as functionality is working fine.
