### ISSUE TITLE
[ Studio > Author > TC_AUTHOR_75 ] Only first unit is visible from Randomized Content Block 

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/wg-build-test-release#287]
I have executed TC_AUTHOR_75 and concluded that after adding some units in libraries and fetching them in the course unit as Randomized Content Block, Only the first unit of that library is visible in the course experience.

**Steps to reproduce:**

1. Go to https://studio.palm.demo.overhang.io/course/course-v1:edX+DemoX+Demo_Course
2. Add a new library having multiple units from problem x blocks and from other x blocks as well.
3. Fetch this library as Randomized Content Block in the course and published it.
4. Now check course experience.

**Expected result:**
All units of the selected library should be visible in the course experience.

**Actual result:**
Only the first unit x block is visible in the studio preview as well as in the Course experience.

<img width="1679" alt="Library" src="https://github.com/openedx/wg-build-test-release/assets/55684124/86e93576-e263-4420-a5cf-bd1409485f5f">

**Comment by mariajgrimaldi** [comment]
I'm gonna research this issue and let you know!

**Comment by eLRuLL** [comment]
@mariajgrimaldi please let us know if you find this to be a bug, sounds like a good first issue for people to contribute

**Comment by mariajgrimaldi** [comment]
Thanks for your patience @fayyazahmed66. This is working for me, this is what I did:

1. Went to https://studio.palm.demo.overhang.io and created a [new library](https://studio.palm.demo.overhang.io/library/library-v1:edX+homework-lib-1) with a few components
2. Login in with the student account and got assigned this component:
![image](https://github.com/openedx/wg-build-test-release/assets/64440265/8481dfae-5380-4226-8d5e-7e5b9de6e0b8)
3. Created a new student account and got assigned this other component:
![image](https://github.com/openedx/wg-build-test-release/assets/64440265/27fe2a9b-af47-4cb6-8b1e-33db86eb5585)

Now, if you configure the randomized library like this in Studio:
![image](https://github.com/openedx/wg-build-test-release/assets/64440265/df3c270b-9488-49a0-88a7-b9584d454823)

You'll get all the components in the course experience: 
[Screencast from 12-06-23 10:25:51.webm](https://github.com/openedx/wg-build-test-release/assets/64440265/035e0a89-1705-4f57-ae59-5a73ee7bdc94)

Can you check again, please? [Here's](https://apps.palm.demo.overhang.io/learning/course/course-v1:edX+DemoX+Demo_Course/block-v1:edX+DemoX+Demo_Course+type@sequential+block@d1dafb033f704dcbb0b6bf32c3d82ae1) the section containing the live configurations I just showed.

**Comment by fayyazahmed66** [comment]
@mariajgrimaldi  Thanks for the detailed instructions and guidance. It's working fine by setting "-1" in the count. I missed that configuration. 
This is not a bug. Should I close it ?

**Comment by mariajgrimaldi** [comment]
Great! Thanks for checking again, I'm closing this now
