### ISSUE TITLE
Palm - End of life Mongo 4.2

### ISSUE THREAD

**Issue by jfavellar90** [openedx/wg-build-test-release#288]
According to Mongo [support policy docs](https://www.mongodb.com/support-policy/lifecycles), version 4.2 reached its end of life on April 2023, and Tutor still uses this version as the default in the [Palm branch](https://github.com/overhangio/tutor/blob/palm/tutor/templates/config/defaults.yml#L17).

I think the schedule for the Palm release is already tight to take such an upgrade into consideration, however, the issue is open to start the conversation.

**Comment by regisb** [comment]
I was not aware that MongoDB had reached EOL. So far MongoDB upgrades have been pretty easy. So I would argue that we should perform the upgrade and that it should be a release blocker.

**Comment by pdpinch** [comment]
FWIW, we've been running Mongo 4.4.x (via the Mongo Atlas service) for some time with olive, palm and master. I would be surprised if there were any issues.

**Comment by regisb** [comment]
I am very tempted to go straight to 6.3...
