### ISSUE TITLE
Communications MFE rewrites links 

### ISSUE THREAD

**Issue by pdpinch** [openedx/wg-build-test-release#294]
The tinyMCE editor in the communications MFE rewrites link URLs from the same server to make them relative links. This obviously doesn't work for end-users when they receive the link in an email. 

Steps to reproduce:

1. Turn on the Communications MFE by setting [`FEATURES['ENABLE_NEW_BULK_EMAIL_EXPERIENCE']`](https://edx.readthedocs.io/projects/edx-platform-technical/en/latest/featuretoggles.html#featuretoggle-FEATURES['ENABLE_NEW_BULK_EMAIL_EXPERIENCE) to True.
2. Navigate to the email section of the Instructor dashboard in a course
3. Start composing an email.
4. add a link to the email, and paste in a URL from the same host
5. use the source code feature to examine the link 

Expected behavior:

When you inspect the link, it should be the same as what you pasted into the add link dialog. 

Actual behavior:

The link is rewritten to make it a relative link.

**Comment by pdpinch** [comment]
This can be fixed by changing the TinyMCE configuration in frontend-app-communciations. 

This worked for us: https://github.com/mitodl/frontend-app-communications/pull/1/commits/caf1c501749bee1ada0ac0323c8c1e45a4ce46e0

**Comment by arbrandes** [comment]
@pdpinch, do you mind submitting a PR to frontend-app-communications with that change?  If you also submit a backport to master, I can approve both at the same time.
