### ISSUE TITLE
Django 3.2.20 security patch (Olive)

### ISSUE THREAD

**Issue by magajh** [openedx/wg-build-test-release#297]
Apply the [3.2.20 security patch](https://www.djangoproject.com/weblog/2023/jul/03/security-releases/) to Olive branches.
```[tasklist]
### Open edX services to upgrade
- [ ] edx-platform
- [ ] enterprise-catalog
- [x] enterprise-access
- [x] ecommerce
- [x] edx-analytics-data-api
- [x] edx-analytics-dashboard
- [x] credentials
- [x] xqueue
- [x] ecommerce-worker
- [x] edx-notes-api
- [x] license-manager
- [x] course-discovery
- [x] blockstore
```

**Comment by mariajgrimaldi** [comment]
Hello! Do we have PR(s) open for this one?

**Comment by magajh** [comment]
Hi @mariajgrimaldi, as far as I am aware, there are no open PR(s) related to this issue

**Comment by magajh** [comment]
I'll take on this issue. I plan to open the corresponding PR(s) (for both Palm and Olive) later today :)
