### ISSUE TITLE
Django 3.2.21 security patch

### ISSUE THREAD

**Issue by magajh** [openedx/wg-build-test-release#303]
Apply the [3.2.21 security patch](https://www.djangoproject.com/weblog/2023/sep/) to Palm branches.
```[tasklist]
### Open edX services to upgrade
- [x] edx-platform
- [ ] enterprise-catalog
- [x] enterprise-access
- [ ] ecommerce
- [ ] edx-analytics-data-api
- [x] edx-analytics-dashboard
- [x] credentials
- [x] xqueue
- [ ] ecommerce-worker
- [x] tubular
- [x] edx-notes-api
- [ ] license-manager
- [x] course-discovery
- [x] blockstore
- [ ] taxonomy-connector
- [x] registrar
- [x] openedxstats
```

**Comment by magajh** [comment]
Hey @mariajgrimaldi, I'm tagging you here in case you want to keep track of this issue for the next Palm release :)

**Comment by mariajgrimaldi** [comment]
Once you have a list of PR(s), please add them here so we can help reviewing. Thanks!

**Comment by mariajgrimaldi** [comment]
What's the procedure when there's a new security patch while the previous ones haven't been merged? A progressive update by patch order?

**Comment by magajh** [comment]
@mariagrimaldi A progressive update doesn't seem necessary, as patch [3.2.22](https://docs.djangoproject.com/en/dev/releases/3.2.22/) is compatible with version 3.2.20. I think we can close this issue, close any remaining open PRs, and then create new PRs to apply the 3.2.22 patch to the respective repositories

**Comment by magajh** [comment]
Update: we're shifting our focus to the latest Django security patch 3.2.23. As a result, this issue and any open PRs related to the Django 3.2.21 patch will be closed.

Please see the new issue for the 3.2.23 patch here: [Issue #306](https://github.com/openedx/wg-build-test-release/issues/306).

**Comment by magajh** [comment]
Update: We're shifting our focus to the latest Django security patch 3.2.23. As a result, this issue and any open PRs related to the Django 3.2.21 patch will be closed.

Please see the new issue for the 3.2.23 patch here: [Issue #306](https://github.com/openedx/wg-build-test-release/issues/306).
