### ISSUE TITLE
MongoDB 4.4 End of Life

### ISSUE THREAD

**Issue by Agrendalath** [openedx/wg-build-test-release#305]
[MongoDB version 4.4 will reach End of Life (EOL) in February 2024](https://endoflife.date/mongodb).

The [Support Windows spreadsheet](https://docs.google.com/spreadsheets/d/11DheEtMDGrbA9hsUvZ2SEd4Cc8CaC4mAfoV8SVaLBGI/edit#gid=195838733&range=G28:AX28) does not list newer MongoDB versions.
```[tasklist]
### Tasks
- [ ] https://github.com/openedx/edx-platform/pull/34213
```

**Comment by Agrendalath** [comment]
This is resolved for `edx-platform` by https://github.com/openedx/edx-platform/pull/34213.

**Comment by mariajgrimaldi** [comment]
Relevant issues:
https://github.com/openedx/public-engineering/issues/245
https://github.com/overhangio/tutor/pull/1029

**Comment by mariajgrimaldi** [comment]
I'll be closing this since the mongodb update was merged in tutor, so it'll be included in redwood.
