### ISSUE TITLE
Backport(s) before quince.1 release

### ISSUE THREAD

**Issue by cmltaWt0** [openedx/wg-build-test-release#307]
## Description
This issue tracks the possible backports to be made before the Quince.1 release dated to: Mon 2023-12-11

https://openedx.atlassian.net/wiki/spaces/COMM/pages/3613392957/Open+edX+Release+Schedule

## Backports
List of backports with their repository, pull request and status. Feel free to fill in this list.

Needed a corresponding backport PRs:

### edx-platform

- [x] https://github.com/openedx/edx-platform/pull/33476
- [x] https://github.com/openedx/edx-platform/pull/33487
- [x] https://github.com/openedx/edx-platform/pull/33656

### cs_comments_service

- [ ] https://github.com/openedx/cs_comments_service/pull/418

### xqueue

- [x] https://github.com/openedx/xqueue/pull/906

### frontend-app-discussions

- [ ] https://github.com/openedx/frontend-app-discussions/pull/575
- [ ] https://github.com/openedx/frontend-app-discussions/pull/578
- [ ] https://github.com/openedx/frontend-app-discussions/pull/583

### frontend-app-communications

- [x] https://github.com/openedx/frontend-app-communications/pull/176

### frontend-app-learner-dashboard

We're just going to keep syncing with master as long as possible:

- [x] https://github.com/openedx/frontend-app-learner-dashboard/pull/243
- [x] https://github.com/openedx/frontend-app-learner-dashboard/pull/257

### frontend-app-course-authoring

- [x] https://github.com/openedx/frontend-app-course-authoring/pull/707

### frontend-app-gradebook

- [x] https://github.com/openedx/frontend-app-gradebook/pull/376

### tutor-mfe

- [x] https://github.com/overhangio/tutor-mfe/pull/173
- [x] https://github.com/overhangio/tutor-mfe/pull/176

### PUBLIC_PATH fixes

- [x] https://github.com/openedx/frontend-app-learning/pull/1209
- [x] https://github.com/openedx/frontend-app-authn/pull/1076
- [x] https://github.com/openedx/frontend-app-account/pull/911
- [x] https://github.com/openedx/frontend-app-communications/pull/158
- [x] https://github.com/openedx/frontend-app-gradebook/pull/356
- [x] https://github.com/openedx/frontend-app-profile/pull/878

The following are still on React Router v5 in `quince.master`, so no PUBLIC_PATH fixes are necessary:

* frontend-app-course-authoring
* frontend-app-discussions
* frontend-app-ora-grading 

### devstack

- [x] https://github.com/openedx/devstack/pull/1150 (removes devpi from devstack, since it was unused and wastes a lot of CPU)
- [x] https://github.com/openedx/devstack/pull/1204
- [x] https://github.com/openedx/devstack/pull/1207

**Comment by ghassanmas** [comment]
Adding this to the list:
- https://github.com/openedx/cs_comments_service/pull/418

**Comment by cmltaWt0** [comment]
Adding to the list:

- https://github.com/openedx/edx-platform/pull/33476 issue link: https://github.com/openedx/wg-build-test-release/issues/308

**Comment by iamsobanjaved** [comment]
Adding to the list:
- https://github.com/openedx/xqueue/pull/906 (backport of Django 4.2 upgrade in xqueue repo)

**Comment by arbrandes** [comment]
All current tutor-mfe MFEs have been fixed so that PUBLIC_PATH works again:

- [x] https://github.com/openedx/frontend-app-learning/pull/1209
- [x] https://github.com/openedx/frontend-app-authn/pull/1076
- [x] https://github.com/openedx/frontend-app-account/pull/911
- [x] https://github.com/openedx/frontend-app-communications/pull/158
- [x] https://github.com/openedx/frontend-app-gradebook/pull/356
- [x] https://github.com/openedx/frontend-app-profile/pull/878

The following are still on React Router v5 in Quince.master, so no PUBLIC_PATH fixes are necessary:

* frontend-app-course-authoring
* frontend-app-discussions
* frontend-app-ora-grading

**Comment by tecoholic** [comment]
Adding to the list for **edx-platform:**

- [ ] https://github.com/openedx/edx-platform/pull/33656

**Comment by tecoholic** [comment]
@mtyaka, @cmltaWt0 Hi, the LTI Provider back-port [above](https://github.com/openedx/wg-build-test-release/issues/307#issuecomment-1794971745) is reviewed and ready. What's needed from my side to get this merged?

**Comment by cmltaWt0** [comment]
> @mtyaka, @cmltaWt0 Hi, the LTI Provider back-port [above](https://github.com/openedx/wg-build-test-release/issues/307#issuecomment-1794971745) is reviewed and ready. What's needed from my side to get this merged?

On it. Want to merge it today.

**Comment by arbrandes** [comment]
New one to add to the list:  https://github.com/openedx/frontend-app-course-authoring/pull/707

**Comment by arbrandes** [comment]
And another:  https://github.com/overhangio/tutor-mfe/pull/173

**Comment by arbrandes** [comment]
And another: https://github.com/overhangio/tutor-mfe/pull/176

**Comment by arbrandes** [comment]
Aaaaand another: https://github.com/openedx/frontend-app-gradebook/pull/376

**Comment by mariajgrimaldi** [comment]
I'll close this now since quince.1 was released a few weeks ago.
