### ISSUE TITLE
Backport request for Quince: openedx-learning 0.2.3

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/wg-build-test-release#308]
Could we please get https://github.com/openedx/edx-platform/pull/33476 merged into the Quince master branch?

For context, this PR squashes a bunch of complex migrations in the `openedx_tagging` and `content_tagging` apps. These apps have not previously been included in any named releases. Over the past months of development, the migrations got a little messy, and we foresee that there will be some problems in the future, so we created a squashed version of the migrations that is much simpler and more robust. We tried to get these in for Quince but missed the initial cutoff by a few hours. So we'd like to get this backport merged. The risk is quite low as there are no user-facing features in Quince that use this code yet; it's just about making sure the database and migrations are in a state that's easily understandable to prevent upgrade issues in the future.

**Comment by mariajgrimaldi** [comment]
@bradenmacdonald: it seems your PR was already merged. I'll close this issue then! Thanks
