### ISSUE TITLE
Django 4.2 upgrade for Quince.1 Release

### ISSUE THREAD

**Issue by cmltaWt0** [openedx/wg-build-test-release#315]
### List of services and corresponding PRs
- [x]  Xqueue (merged on master after branch cut, here is [the backport PR](https://github.com/openedx/xqueue/pull/906))
- [x]  Discovery (upgrade is currently on stage, and backport PR is yet to be created) (PR)[https://github.com/openedx/course-discovery/pull/4158]
- [x]  Notes (Updated on master and backport PR is yet to be created) (PR)[https://github.com/openedx/edx-notes-api/pull/376]
- [ ]  Ecommerce (not yet ready, probably will be available before quince.2)
- [x]  edx-platform (ready, can't merge on master yet, can be backported) (PR)[https://github.com/openedx/edx-platform/pull/33516]

### Upgrade plan
https://openedx.atlassian.net/wiki/spaces/AC/pages/3767926815/Django+4.2+Upgrade+Plan

### Tutor related updates
- [x] https://github.com/overhangio/tutor/pull/929
- [x] https://github.com/overhangio/tutor-mfe/pull/159

**Comment by iamsobanjaved** [comment]
We have upgraded Django on edx.org and here is the backport PR for Quince for course-discovery.
- https://github.com/openedx/course-discovery/pull/4158

**Comment by iamsobanjaved** [comment]
PR to upgrade Django 4.2 in the edx-platform in the Quince release is ready:
- https://github.com/openedx/edx-platform/pull/33516

**Comment by mariajgrimaldi** [comment]
Hi folks. @cmltaWt0: why can we merge the edx-platform upgrade to quince bot not master?

**Comment by iamsobanjaved** [comment]
> Hi folks. @cmltaWt0: why can we merge the edx-platform upgrade to quince but not master?

We have PR (https://github.com/openedx/edx-platform/pull/33211) ready for merging on master, but we are still waiting for MySQL 8.0 upgrade to land on the production instance and also waiting for our sessions to be hashed with the new hashing algorithm. So we wanted to give it first to the Quince release.

Hashing Algorithm Change: https://github.com/edx/edx-arch-experiments/issues/453

More details on Slack: https://openedx.slack.com/archives/C049JQZFR5E/p1697203704251089

@mariajgrimaldi

**Comment by cmltaWt0** [comment]
@mariajgrimaldi We have Django 3.2 EOL on 01 Apr 2024 - before Redwood so we have to land it in Quince in any case.
We are waiting for it be landed to master for sure.
We can test and merge other PR (for xqueue, discovery) for now.

**Comment by mariajgrimaldi** [comment]
I agree with @cmltaWt0. I'd prefer to wait for it to land in master, but I'm worried about the release timeline. We need to have a bit of time to test it out. @iamsobanjaved, do we have an estimate for merging the masters' PR? I'm also thinking we could benefit from the update early on in the testing process.

**Comment by iamsobanjaved** [comment]
We don't yet have any timeline for MySQL 8.0 upgrade on prod and hence blocked on it, there is an active effort on upgradation but facing certain issues. Also, we might have to wait for at least two weeks for old sessions to be replaced with new sessions. We have added all support commits on edx-platform master before branch cut and now only this last PR is remaining. 

My rationale for merging it into the release branch as soon as possible is that Open edX conducts rigorous testing on this branch. This way, if there are any errors, they can be detected during testing, and we can promptly provide fixes for them. 

But it is up to you guys to decide what fits for you.

**Comment by mariajgrimaldi** [comment]
As I said, I usually agree with waiting for the master merge. But we should test this as soon as possible to identify any issues. @cmltaWt0 what do you think?

**Comment by cmltaWt0** [comment]
Regarding the current state I can agree with the reasoning to merge it to the release branch so we can catch any weird behaviour.
Let's at least build the openedx image and run locally before merge.

**Comment by mariajgrimaldi** [comment]
Great! Thank you both

**Comment by cmltaWt0** [comment]
Just tested it.
It looks like we can't merge it without tutor preparation for the upgrade.

`tutor local launch` gives me an Import error on this [line](https://github.com/overhangio/tutor/blob/nightly/tutor/templates/apps/openedx/settings/partials/common_all.py#L152).
```
from django.utils.deprecation import RemovedInDjango40Warning, RemovedInDjango41Warning
```

```
File "/openedx/edx-platform/lms/envs/tutor/production.py", line 156, in <module>
    from django.utils.deprecation import RemovedInDjango40Warning, RemovedInDjango41Warning
ImportError: cannot import name 'RemovedInDjango40Warning' from 'django.utils.deprecation' (/openedx/venv/lib/python3.8/site-packages/django/utils/deprecation.py)
```

**Comment by cmltaWt0** [comment]
It seems the process may be more complicated :)
```
ERRORS:
?: (4_0.E001) As of Django 4.0, the values in the CSRF_TRUSTED_ORIGINS setting must start with a scheme (usually http:// or https://) but found apps.local.overhang.io. See the release notes for details.
```
So we have to update `tutor-mfe` nightly as well (and probably any other IDA plugins).

**Comment by mariajgrimaldi** [comment]
Pff. Thanks for testing that out! Should we open an issue in the tutor repository for the migration? So everyone is in sync.

**Comment by cmltaWt0** [comment]
Yeap. Definitely.

**Comment by cmltaWt0** [comment]
I've manage to build and run the Django 4.2 for lms/cms and mfe container.
It works for the first look. Will create PRs for tutor and tutor-mfe.

**Comment by iamsobanjaved** [comment]
> Just tested it. It looks like we can't merge it without tutor preparation for the upgrade.
> 
> `tutor local launch` gives me an Import error on this [line](https://github.com/overhangio/tutor/blob/nightly/tutor/templates/apps/openedx/settings/partials/common_all.py#L152).
> 
> ```
> from django.utils.deprecation import RemovedInDjango40Warning, RemovedInDjango41Warning
> ```
> 
> ```
> File "/openedx/edx-platform/lms/envs/tutor/production.py", line 156, in <module>
>     from django.utils.deprecation import RemovedInDjango40Warning, RemovedInDjango41Warning
> ImportError: cannot import name 'RemovedInDjango40Warning' from 'django.utils.deprecation' (/openedx/venv/lib/python3.8/site-packages/django/utils/deprecation.py)
> ```

You can replace with Django50 and 51 warnings.



> It seems the process may be more complicated :)
> 
> ```
> ERRORS:
> ?: (4_0.E001) As of Django 4.0, the values in the CSRF_TRUSTED_ORIGINS setting must start with a scheme (usually http:// or https://) but found apps.local.overhang.io. See the release notes for details.
> ```
> 
> So we have to update `tutor-mfe` quince as well (and probably any other IDA plugins).

Yes we need this change, also mentioned in the quince release notes here: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3726802953/Pending+Release+Quince#Operational-%E2%9A%99%EF%B8%8F

**Comment by mariajgrimaldi** [comment]
@iamsobanjaved: did you folks consider this change when upgrading to Django 4.x? https://github.com/openedx/wg-build-test-release/issues/325#issuecomment-1808618884

**Comment by iamsobanjaved** [comment]
Yes we were aware of this change but we already had our host in `CSRF_TRUSTED_ORIGINS` so we just had to add the scheme, added this to Quince Release [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3726802953/Pending+Release+Quince#Operational-%E2%9A%99%EF%B8%8F)

**Comment by mariajgrimaldi** [comment]
@iamsobanjaved: so you folks no only add the MFE domains but all subdomains, right?
