### ISSUE TITLE
Settings and Features toggles changes between Palm to Quince 

### ISSUE THREAD

**Issue by ghassanmas** [openedx/wg-build-test-release#316]
## New settings:

-  `EXAMS_DASHBOARD_MICROFRONTEND_URL`  [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/lms/envs/common.py#L4992)
- `ELASTIC_SEARCH_INDEX_PREFIX` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/lms/envs/common.py#L1410)

## New Features toggles
- `CREATE_COURSE_WITH_DEFAULT_ENROLLMENT_START_DATE` [ref](https://github.com/openedx/edxplatform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/xmodule/course_block.py#L61)
- `SHOW_REGISTRATION_LINKS` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/lms/envs/common.py#L782)
- `IGNORED_ERRORS[N]['LOG_ERROR']` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/openedx/core/lib/request_utils.py#L155)
- `IGNORED_ERRORS[N]['LOG_STACK_TRACE']` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/openedx/core/lib/request_utils.py#L162)
- `SEND_CERTIFICATE_CREATED_SIGNAL` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/lms/djangoapps/certificates/config.py#L20)
- `SEND_CERTIFICATE_REVOKED_SIGNAL` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/lms/djangoapps/certificates/config.py#L33)
- `TPA_AUTOMATIC_LOGOUT_ENABLED` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/lms/envs/common.py#L1263)
- `content_tagging.auto` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/openedx/core/djangoapps/content_tagging/toggles.py#L8)
- `contentstore.default_enable_flexible_peer_openassessments` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/cms/djangoapps/contentstore/toggles.py#L519)
- `contentstore.enable_copy_paste_units` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/cms/djangoapps/contentstore/toggles.py#L201)
- `contentstore.enable_studio_content_api` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/cms/djangoapps/contentstore/toggles.py#L217)
- `contentstore.mock_video_uploads` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/cms/djangoapps/contentstore/toggles.py#L500)
- `contentstore.new_studio_mfe.use_new_advanced_settings_page` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/cms/djangoapps/contentstore/toggles.py#L300)
- `contentstore.new_studio_mfe.use_new_course_outline_page` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/cms/djangoapps/contentstore/toggles.py#L440)
- `contentstore.new_studio_mfe.use_new_course_team_page` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/cms/djangoapps/contentstore/toggles.py#L480)
- `contentstore.new_studio_mfe.use_new_custom_pages` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/cms/djangoapps/contentstore/toggles.py#L260)
- `contentstore.new_studio_mfe.use_new_export_page` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/cms/djangoapps/contentstore/toggles.py#L380)
- `contentstore.new_studio_mfe.use_new_files_uploads_page` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/cms/djangoapps/contentstore/toggles.py#L400)
- `contentstore.new_studio_mfe.use_new_grading_page` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/cms/djangoapps/contentstore/toggles.py#L320)
- `contentstore.new_studio_mfe.use_new_import_page` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/cms/djangoapps/contentstore/toggles.py#L360)
- `contentstore.new_studio_mfe.use_new_schedule_details_page` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/cms/djangoapps/contentstore/toggles.py#L280)
- `contentstore.new_studio_mfe.use_new_unit_page` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/cms/djangoapps/contentstore/toggles.py#L460)
- `contentstore.new_studio_mfe.use_new_updates_page` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/cms/djangoapps/contentstore/toggles.py#L340)
- `contentstore.new_studio_mfe.use_new_video_uploads_page` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/cms/djangoapps/contentstore/toggles.py#L420)
- `course_experience.relative_dates_disable_reset` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/openedx/features/course_experience/__init__.py#L55)
- `course_home.course_home_mfe_progress_tab` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/lms/djangoapps/course_home_api/toggles.py#L9)
- `courseware.learning_assistant` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/lms/djangoapps/courseware/toggles.py#L112)
- `courseware.mfe_courseware_search` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/lms/djangoapps/courseware/toggles.py#L58)
- `learner_dashboard.enable_b2c_subscriptions` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/lms/djangoapps/learner_dashboard/config/waffle.py#L41)
- `new_core_editors.use_video_gallery_flow` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/cms/djangoapps/contentstore/toggles.py#L125)
- `new_editors.add_game_block_button` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/cms/djangoapps/contentstore/toggles.py#L162)
- `new_studio_mfe.use_new_home_page` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/cms/djangoapps/contentstore/toggles.py#L241)
- `notifications.enable_notifications` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/openedx/core/djangoapps/notifications/config/waffle.py#L10)
- `notifications.show_notifications_tray` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/openedx/core/djangoapps/notifications/config/waffle.py#L21)
- `xblocks.xblock_skill_tag_verification` [ref](https://github.com/openedx/edx-platform/blob/d3d203cbac609adf23a6a8f003731fef12bd1ea1/xmodule/vertical_block.py#L38)

## ❌ Removed Features toggles
- `BLOCK_STRUCTURES_SETTINGS['PRUNING_ACTIVE']`
- `EXPECTED_ERRORS[N]['IS_IGNORED']` 
- `EXPECTED_ERRORS[N]['LOG_ERROR']`
- `EXPECTED_ERRORS[N]['LOG_STACK_TRACE']`
- `block_structure.invalidate_cache_on_publish`
- `contentstore.enable_copy_paste_feature`
- `learner_home_mfe.enable_learner_home_amplitude_recommendations`
- `registration.enable_failure_logging`

Related issues: 
- Palm #260 
- Olive #204

**Comment by feoh** [comment]
This is set. Closing.
