### ISSUE TITLE
[Test failure] TC_LEARNER_7: Can't create an account

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-build-test-release#318]
### Release

Quince

### Expected behavior

"Register" lets me create an account

### Actual behavior

> Error: We couldn't create your account.
> Please check your responses and try again.

### Steps to reproduce

* Go to https://apps.quince.demo.edly.io/authn/register?next=%2F
* Try to make an account

### Additional information

![image](https://github.com/openedx/wg-build-test-release/assets/3628148/56f90127-6d94-49af-9e95-a5751d17f103)

Notes:

* I would post the failed network request, but I don't see one. I think the error might be happening in the client side.
* I don't see any JS errors in the browser console either.
* ~I am noticing the same behavior on a laptop installation of Tutor Nightly, both in local and dev modes.~
  * ~In that same laptop installation, I'm getting this JWT issue when trying to log in, which Toby has a suggested fix for: https://discuss.openedx.org/t/tutor-nightly-login-error-rsa-key-must-include-all-parameters-if-any-are-present-besides-d/11479~
  * ^ This [turned out to be unrelated](https://github.com/openedx/wg-build-test-release/issues/318#issuecomment-1779429990).

**Comment by sambapete** [comment]
@kdmccormick I definitely encountered the same issue on the demo / test server. I didn't report it yet as I was giving time to  @regisb in order to fix potential issues with the MFEs that were made available earlier today by @arbrandes. Thanks for reporting it.

**Comment by fayyazahmed66** [comment]
Same. I am also not able to register. 
<img width="1666" alt="signup" src="https://github.com/openedx/wg-build-test-release/assets/55684124/d0c57095-82d3-4661-8026-4c31f2106fdd">

**Comment by sambapete** [comment]
Still unable to create an account after Dean officially announced testing earlier today.

**Comment by kdmccormick** [comment]
In my notes I said:

> I am noticing the same behavior on a laptop installation of Tutor Nightly, both in local and dev modes.
> * In that same laptop installation, I'm getting this JWT issue when trying to log in, which Toby has a suggested fix for: https://discuss.openedx.org/t/tutor-nightly-login-error-rsa-key-must-include-all-parameters-if-any-are-present-besides-d/11479

Unfortunately, this turned out to be a separate issue, caused by the [pyjkest->pyjwt upgrade](https://github.com/openedx/edx-platform/pull/32270) which merged _after_ the Quince cut. (it's now [fixed in Tutor nightly](https://github.com/overhangio/tutor/pull/925)).

So, we currently have no leads on what might be causing this.

Is there anyone with an account already created that can confirm whether login works? Or are we all locked out right now?

**Comment by mariajgrimaldi** [comment]
@kdmccormick: I logged in using the default credentials listed [here](https://github.com/overhangio/openedx-release-demo#open-edx-release-demo-platform-cd), but of course I didn't create the account.

**Comment by regisb** [comment]
This is definitely a critical issue, but please don't let it block your testing. You can login with existing admin or student credentials:

- Student user:
        - username: student
        - email: [student@overhang.io](mailto:student@overhang.io)
        - password: student
- Administrator user:
        - username: admin
        - email: [admin@overhang.io](mailto:admin@overhang.io)
        - password: admin

**Comment by ghassanmas** [comment]
I've been looking into this and I am sitll debuggin it, I will report here as soon as I find something or open a PR..etc

**Comment by ghassanmas** [comment]
Regarding the account creation issue, I opened a PR upstream to fix it https://github.com/openedx/frontend-app-authn/pull/1099 I am sure it will resolve it but I am not sure if it’s the best solution… I think at least we know now, where is it coming from; _The Country Field_

**Comment by mariajgrimaldi** [comment]
I tested this on my local environment, which worked like a charm! Now I'm wondering what changed that now is failing.

**Comment by ghassanmas** [comment]
> Now I'm wondering what changed that now is failing. @ghassanmas: do you have a clue on what could have happened? 🤔 

@mariajgrimaldi I didn't quite get that, could you elobrate please? What is failing exactly?

**Comment by mariajgrimaldi** [comment]
@ghassanmas: the registration process

**Comment by ghassanmas** [comment]
It still fails on edly (the main sandbox) because still my PR, needs to be merged and backported. Or do you mean it stills fails for you locally?

**Comment by mariajgrimaldi** [comment]
@ghassanmas: I tested locally and it's working. I meant why it's failing in quince. Sorry if I wasn't clear😅

**Comment by regisb** [comment]
I deployed Ghassan's fix on the demo server, so users should be able to sign up. Again, this is a temporary fix and we will need to merge (and backport) [Ghassan's PR](https://github.com/openedx/frontend-app-authn/pull/1099) before the Quince release.

**Comment by mariajgrimaldi** [comment]
This was fixed by the PR linked above.

**Comment by fayyazahmed66** [comment]
@mariajgrimaldi  Verified. Thanks.
