### ISSUE TITLE
[TC_AUTHOR_17] > Not able to access course

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/wg-build-test-release#319]
Got an error while trying to start a course who's first section start date is of the future.
**Steps to reproduce:**

1. Go to this course https://apps.quince.demo.edly.io/learning/course/course-v1:arbisoft+AR2000+2000/home
2. Click on the view course button from the dashboard 
**Expected result:**
It should start the course and take me to the course page
**Actual result:**
Throwing a 404 error.

<img width="1678" alt="pages and resourcses" src="https://github.com/openedx/wg-build-test-release/assets/55684124/9306c412-8631-4c99-bc3e-bba978f58df0">

**Comment by fayyazahmed66** [comment]
label: quince testing

**Comment by mariajgrimaldi** [comment]
@fayyazahmed66: early this year we create a template for reporting testing failures, pretty similar to your issue description but it'd be beneficial to use it so we know we're capturing the right information. Thanks!
You can find the template when creating a new issue: New issue > 📑 Test failure report

**Comment by mariajgrimaldi** [comment]
label: quince testing

**Comment by mariajgrimaldi** [comment]
It works when loading the [Demonstration Course](https://apps.quince.demo.edly.io/learning/course/course-v1:edX+DemoX+Demo_Course/home) but yours fails. I'm getting this error:
![image](https://github.com/openedx/wg-build-test-release/assets/64440265/95a7e25c-3e8c-46a1-9078-a971b7bf92d0)

**Comment by DeanJayMathew** [comment]
I am getting the same error with a new course that has not started yet. When the course starts, the issue is no longer present. In the meantime you can get to the unit level through Studio's "Preview" and "View Live Version" buttons.

**Comment by fayyazahmed66** [comment]
> @fayyazahmed66: early this year we create a template for reporting testing failures, pretty similar to your issue description but it'd be beneficial to use it so we know we're capturing the right information. Thanks! You can find the template when creating a new issue: New issue > 📑 Test failure report

@mariajgrimaldi  Sure. Noted.

**Comment by mariajgrimaldi** [comment]
This is happening to me as well in my tutor nightly installation. I opened an issue in the learning MFE repo: https://github.com/openedx/frontend-app-learning/issues/1240

**Comment by arbrandes** [comment]
The fix is up for review:

https://github.com/overhangio/tutor-mfe/pull/173

**Comment by mariajgrimaldi** [comment]
This is working as expected with a course with a date in the future: https://apps.quince.demo.edly.io/learning/course/course-v1:DEMO+demo-v1+2023/home
