### ISSUE TITLE
[Enable wiki and discussion] <TC_AUTHOR_86>: <Pages and resources link isn't working >

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/wg-build-test-release#320]
### Release

quince

### Expected behavior

By clicking on the Pages and Resources page under the content drop-down, It should open the page.

### Actual behavior

The black page appears.

### Steps to reproduce

1. Go to studio
2. select any course and click on the content drop-down
3. Click on the Pages and Resources link drop-down

### Additional information

<img width="1678" alt="pages and resourcses" src="https://github.com/openedx/wg-build-test-release/assets/55684124/1c73889f-d2db-4a60-95b4-d2567ca639a6">

**Comment by mariajgrimaldi** [comment]
@fayyazahmed66 can you test again? For some reason, I can access the pages & resources view.

**Comment by mariajgrimaldi** [comment]
I'll close the issue since it's working on the demo server.

**Comment by fayyazahmed66** [comment]
@mariajgrimaldi  Verified. Thanks.
