### ISSUE TITLE
[Cursor shape on hovering] <TC_AUTHOR_81>: <hovering over "Cancel" button, cursor does not changes to hand icon>

### ISSUE THREAD

**Issue by mdsulemanr** [openedx/wg-build-test-release#322]
### Release

Quince

### Expected behavior

When we hover over the "Cancel" button, the cursor should be changed to hand icon.

### Actual behavior

the cursor remains in an "I-beam" shape ["I"]

### Steps to reproduce

1. Go to studio
2. Select any course and go to Updates under content
3. Press "Delete" on any existing one (or first add one if do not exist any)
4. Hover over the "Cancel" button on the Popup

### Additional information

Although the "Cancel" button is working fine, we can fix this UI issue for an even better user experience.
![update](https://github.com/openedx/wg-build-test-release/assets/42205023/21c03716-20dd-4a4e-828f-675e1ec44490)

**Comment by mdsulemanr** [comment]
label: quince testing

**Comment by DeanJayMathew** [comment]
@mdsulemanr nice catch!
