### ISSUE TITLE
[Test failure] <TC_LEARNER_8>: <Not able to receive account activation or any other emails>

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/wg-build-test-release#327]
### Release

quince

### Expected behavior

Users should be able to receive emails against a valid email ID.

### Actual behavior

Emails aren't coming. 

### Steps to reproduce

1. Go to https://apps.quince.demo.edly.io/authn/register?next=%2F
2. Register a user with valid data and email id
3. check your inbox 

### Additional information

Emails are not coming on other areas like bulk enrolment etc.

**Comment by mariajgrimaldi** [comment]
I can confirm I didn't get the registration email, not even on my spam inbox. Did we get any error messages in the server logs? @regisb

**Comment by mariajgrimaldi** [comment]
label: quince testing
