### ISSUE TITLE
[Quince testing] <TC_AUTHOR_45>: <Getting incorrect format and studio error on some advance problem xblocks>

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/wg-build-test-release#328]
### Release

quince

### Expected behavior

By default, xblocks should be added successfully with the correct formatting.

### Actual behavior

`Problem with Adaptive Hint`, `Custom JavaScript Display and Grading` and `Custom Python-Evaluated Input` are giving studio and formatting errors. ,

### Steps to reproduce

1. Go to studio.
2. add mentioned advance problem xblocks or go to this URL : https://studio.quince.demo.edly.io/container/block-v1:edly+ARD200+2001+type@vertical+block@cafcf2e4825747b38415f291afbda672

### Additional information

<img width="1440" alt="Screenshot 2023-11-22 at 11 19 35 AM" src="https://github.com/openedx/wg-build-test-release/assets/55684124/3672f728-7178-4b9c-ab03-c01fc29a28f6">
00-4b4f-848d-9788feb614de">
<img width="1420" alt="Screenshot 2023-11-22 at 11 21 34 AM" src="https://github.com/openedx/wg-build-test-release/assets/55684124/88fca698-4974-4564-892e-3eb2c8073036">

<img width="1433" alt="Screenshot 2023-11-22 at 11 24 59 AM" src="https://github.com/openedx/wg-build-test-release/assets/55684124/c3fb8d74-2e11-4c2e-852a-e80596f9f41d">

**Comment by mariajgrimaldi** [comment]
I opened a PR for this issue: https://github.com/overhangio/openedx-release-demo/pull/41

**Comment by mariajgrimaldi** [comment]
label: quince testing

**Comment by mariajgrimaldi** [comment]
@fayyazahmed66: this should be fixed now. Can you help me test again? Thanks!

**Comment by mariajgrimaldi** [comment]
This is working as expected with the advanced problems reported in the issue: https://apps.quince.demo.edly.io/learning/course/course-v1:DEMO+adv-v1+2023/block-v1:DEMO+adv-v1+2023+type@sequential+block@6825f0f94bd14919b275ff5c05fdb1fa/block-v1:DEMO+adv-v1+2023+type@vertical+block@13e6a42f1d09464faa8387e29f33fdf5
