### ISSUE TITLE
[Quince Test failure] <TC_INSTRUCTOR_9>: <View gradebook : Page is blank>

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/wg-build-test-release#329]
### Release

quince

### Expected behavior

It should open the grade book page.

### Actual behavior

The page appears as a blank page.

### Steps to reproduce

1. Go to the instructor dashboard of any course as a course instructor
2. Go to the student admin tab 
3. Click on view grade book (link: https://apps.quince.demo.edly.io/gradebook/course-v1:edly+ARD200+2001)

### Additional information

<img width="1440" alt="Screenshot 2023-11-22 at 4 23 57 PM" src="https://github.com/openedx/wg-build-test-release/assets/55684124/185d2301-b334-4519-9085-8710c60d8251">

**Comment by mariajgrimaldi** [comment]
label: quince testing

**Comment by arbrandes** [comment]
This is the fix to master: https://github.com/openedx/frontend-app-gradebook/pull/375

**Comment by arbrandes** [comment]
Even though the fix to master is still pending a review, I merged the backport so this should now be fixed for Quince.

**Comment by mariajgrimaldi** [comment]
With the latest deployment I can load the gradebook MFE: https://apps.quince.demo.edly.io/gradebook/course-v1:Axim+TC01+test
