### ISSUE TITLE
[LMS] <TC_INSTRUCTOR_5>: <Course content is giving error if it has future start date>

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/wg-build-test-release#331]
### Release

quince

### Expected behavior

It should show content to the instructor

### Actual behavior

It gives the error "An unexpected error occurred. Please click the button below to refresh the page."

### Steps to reproduce

1. Create a course with a future start date
2. view the course from the LMS dashboard
3. or click https://apps.quince.demo.edly.io/learning/course/course-v1:edly+ed101+101/home

### Additional information

<img width="1436" alt="Screenshot 2023-11-28 at 4 57 21 PM" src="https://github.com/openedx/wg-build-test-release/assets/55684124/0587eb8b-b865-4b64-b2fe-449fd080f58a">

**Comment by mariajgrimaldi** [comment]
label: quince testing

**Comment by arbrandes** [comment]
The fix is up for review:

https://github.com/overhangio/tutor-mfe/pull/173

**Comment by mariajgrimaldi** [comment]
This is working now: https://apps.quince.demo.edly.io/learning/course/course-v1:DEMO+demo-v1+2023/block-v1:DEMO+demo-v1+2023+type@sequential+block@d5f1bb1bdc7047069c94f2867256bdb3/block-v1:DEMO+demo-v1+2023+type@vertical+block@6732a8b336a34565b8db8b32e12aeb08
