### ISSUE TITLE
[LEARNER] <LMS: PROFILE> Upload photo

### ISSUE THREAD

**Issue by cmltaWt0** [openedx/wg-build-test-release#333]
### Release

Quince

### Expected behavior

The profile photo should be available after upload in the Profile MFE.

### Actual behavior

The profile photo doesn't appear.
500 LMS Error:
```
tutor_local-lms-1  |   File "/openedx/edx-platform/./openedx/core/djangoapps/profile_images/views.py", line 159, in post
tutor_local-lms-1  |     create_profile_images(uploaded_file, profile_image_names)
tutor_local-lms-1  |   File "/openedx/edx-platform/./openedx/core/djangoapps/profile_images/images.py", line 63, in create_profile_images
tutor_local-lms-1  |     storage = get_profile_image_storage()
tutor_local-lms-1  |   File "/openedx/edx-platform/./openedx/core/djangoapps/user_api/accounts/image_helpers.py", line 30, in get_profile_image_storage
tutor_local-lms-1  |     return storage_class(**config['options'])
tutor_local-lms-1  |   File "/openedx/venv/lib/python3.8/site-packages/storages/backends/s3.py", line 280, in __init__
tutor_local-lms-1  |     super().__init__(**settings)
tutor_local-lms-1  |   File "/openedx/venv/lib/python3.8/site-packages/storages/base.py", line 15, in __init__
tutor_local-lms-1  |     raise ImproperlyConfigured(
tutor_local-lms-1  | django.core.exceptions.ImproperlyConfigured: Invalid setting 'base_url' for S3Storage
```

### Steps to reproduce

1. Go to Account MFE and setup a birthday to be 13+
2. Go to Profile MFE
3. Click Upload photo 
![image](https://github.com/openedx/wg-build-test-release/assets/877401/627f4f07-81ea-4a69-b81f-d3edfdd0fed4)

### Additional information

The issue can be fixed by removing 
```
# the following non empty property is necessary in development
"base_url": "dummyprofileimagebaseurl",
```
in openedx-lms-common-settings.
Need to test `development` local deployment.

**Comment by regisb** [comment]
This is an issue of the minio plugin, right? @FahadKhalid210 can you please have a look?

**Comment by regisb** [comment]
This issue was resolved by @FahadKhalid210 with a fix in the tutor-minio plugin. I can confirm that I am now able to upload profile pictures:

![image](https://github.com/openedx/wg-build-test-release/assets/44319/2cd4efe8-88f6-4795-ab83-a6c1b629618a)


Thanks Fahad!
