### ISSUE TITLE
[Pages&Resourses] <TC_AUTHOR_86>: <Not able to disable any feature>

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/wg-build-test-release#334]
### Release

quince

### Expected behavior

Clicking on Gear Icon should open enable disable settings

### Actual behavior

Clicking on gear icon does nothing. 

### Steps to reproduce

1. Go to studio
2. select any course and click on the content drop-down
3. Click on the Pages and Resources link drop-down
4. Click on gear icon

### Additional information

<img width="1438" alt="Screenshot 2023-12-07 at 10 16 43 AM" src="https://github.com/openedx/wg-build-test-release/assets/55684124/aea8fc73-ce1c-4fad-92f0-4ed896334e04">

**Comment by mariajgrimaldi** [comment]
label: quince testing

**Comment by arbrandes** [comment]
I tested it locally, and it was likely fixed by https://github.com/overhangio/tutor-mfe/pull/173.

**Comment by mariajgrimaldi** [comment]
@arbrandes @regisb: let us know when the change is deployed in the demo site so we can test again. Thanks!

**Comment by regisb** [comment]
Done!

**Comment by mariajgrimaldi** [comment]
@fayyazahmed66: can you please help us test again?

**Comment by mariajgrimaldi** [comment]
With the latest changes in tutor-mfe, I was able to display the modals for disabling features: https://apps.quince.demo.edly.io/course-authoring/course/course-v1:edX+DemoX+Demo_Course/pages-and-resources

**Comment by fayyazahmed66** [comment]
@mariajgrimaldi  Verified. Things are working as per expectations.
Thanks
