### ISSUE TITLE
[Enable wiki and discussion] <TC_AUTHOR_86>: <Discussion page is giving error >

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/wg-build-test-release#335]
### Release

quince

### Expected behavior

Discussion page should open.

### Actual behavior

Getting error.

### Steps to reproduce

1. Go to studio
2. select any course and click on the content drop-down
3. Click on the Pages and Resources link drop-down
4. Click view live button and then click on discussion tab

### Additional information

<img width="1440" alt="Screenshot 2023-12-06 at 11 11 34 AM" src="https://github.com/openedx/wg-build-test-release/assets/55684124/c29c7109-386e-4b07-94bf-03ccfce3a118">

**Comment by arbrandes** [comment]
With the latest fixes in tutor-mfe I cannot reproduce this problem anymore.  Discussions seem to work fine.

**Comment by mariajgrimaldi** [comment]
@arbrandes @regisb: let us know when the change is deployed in the demo site so we can test again. Thanks!

**Comment by regisb** [comment]
Done!

**Comment by mariajgrimaldi** [comment]
@fayyazahmed66: can you please help us test again?

**Comment by mariajgrimaldi** [comment]
The discussion page is working as expected: https://apps.quince.demo.edly.io/discussions/course-v1:edX+DemoX+Demo_Course/posts

**Comment by fayyazahmed66** [comment]
@mariajgrimaldi  Verified. Thanks.
