### ISSUE TITLE
Backport(s) before quince.2 release

### ISSUE THREAD

**Issue by cmltaWt0** [openedx/wg-build-test-release#337]
## Description
This issue tracks the possible backports to be made before the Quince.2 release dated to: ~ 2024-02-09

https://openedx.atlassian.net/wiki/spaces/COMM/pages/3613392957/Open+edX+Release+Schedule

## Backports
List of backports with their repository, pull request and status. Feel free to fill in this list.

**Comment by mariajgrimaldi** [comment]
Here's the list of PRs currently opened against the `quince.master` branch on the openedx org: https://github.com/search?q=org%3Aopenedx%20is%3Apr%20is%3Aopen%20base%3Aopen-release%2Fquince.master%20&type=pullrequests
