### ISSUE TITLE
[Test failure] <TC_AUTHOR_69>: <LTI Consumer isn't working and giving 502 bad gateway error>

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/wg-build-test-release#340]
### Release

quince

### Expected behavior

User should be able to update LTI consumer urls and it should save without giving errors.

### Actual behavior

Getting 502 bad gateway.

### Steps to reproduce

1. Go to studio
2. add LTI consumer and try to save it after giving the correct urls
3. click on save button 

### Additional information

link: https://studio.sandbox.openedx.edly.io/container/block-v1:edX+DemoX+Demo_Course+type@vertical+block@b01aa2c53b064c579812ba446299d812

Image : 
![Uploading Screenshot 2024-02-19 at 12.27.52 PM.png…]()

**Comment by mariajgrimaldi** [comment]
Hello there! Thanks for the report. Have you tried this in a different environment? Or locally?

**Comment by mariajgrimaldi** [comment]
@DonatoBD will try to reproduce this issue in the Sandbox. Please, let us know what you find!

**Comment by DonatoBD** [comment]
Hi @fayyazahmed66, I did a test last week in https://studio.sandbox.openedx.edly.io/ using [this page to test the LTI](https://saltire.lti.app/tool) component and as you can see I had no problems

![Screenshot from 2024-05-02 20-35-22](https://github.com/openedx/wg-build-test-release/assets/77167078/6c370a28-e711-4fab-9937-9bfe63505b02)

![Screenshot from 2024-05-02 20-35-10](https://github.com/openedx/wg-build-test-release/assets/77167078/071a3c11-cd57-4ef4-b276-c42c0908542a)

![Screenshot from 2024-05-02 20-34-58](https://github.com/openedx/wg-build-test-release/assets/77167078/1e6c2470-4811-4007-8d33-35923a06affb)

![Screenshot from 2024-05-02 20-34-48](https://github.com/openedx/wg-build-test-release/assets/77167078/ec7183bf-6e3a-41a3-8969-c3366d88cfa9)

I also tested it locally and could not replicate what you reported. Is there any special condition needed to replicate it or it was already solved?

**Comment by mariajgrimaldi** [comment]
I believe this was environment-related, so I'll be closing this now. If any other issue arises during Redwood testing, we'll take care of it separately. Thank you both!
