### ISSUE TITLE
Apply Django security patches for Quince (4.2.11 and 3.2.25)

### ISSUE THREAD

**Issue by magajh** [openedx/wg-build-test-release#341]
Apply latest Django security releases (5.0.3, 4.2.11, and 3.2.25): https://www.djangoproject.com/weblog/2024/mar/04/security-releases/

### Open edX services to upgrade

- [x] course-discovery
- [x] credentials
- [x] ecommerce-worker
- [x] ecommerce
- [x] edx-analytics-dashboard
- [x] edx-analytics-data-api
- [x] edx-notes-api
- [x] edx-platform
- [x] enterprise-access
- [x] enterprise-catalog
- [x] license-manager
- [x] xqueue
- [x] xblock-skill-tagging

**Comment by cmltaWt0** [comment]
@magajh Thanks for your work!

P.S. To use an identical branch names it's incredibly useful for testing, thanks for that!
