### ISSUE TITLE
Certificates need more spaces between signatures

### ISSUE THREAD

**Issue by mariajgrimaldi** [openedx/wg-build-test-release#342]
After fixing https://github.com/openedx/wg-build-test-release/issues/274, signatures now need more spaces between them.

See https://github.com/openedx/wg-build-test-release/issues/274#issuecomment-1780817964 for more context.

**Comment by mariajgrimaldi** [comment]
@BetoFandino: thank you for the help!

**Comment by BetoFandino** [comment]
![image](https://github.com/openedx/wg-build-test-release/assets/39286595/ffe260a1-3603-494e-8c5b-c534a8d59a84)

Hello everyone, the problem seems to have been solved earlier. I have tested in two environments and in both of them everything seems to be in order with the spacing between signatures.

**Comment by mariajgrimaldi** [comment]
Great @BetoFandino! I'll be closing this now then. Thank you for the help!
