### ISSUE TITLE
Apply Django security patches before Redwood release cut

### ISSUE THREAD

**Issue by magajh** [openedx/wg-build-test-release#343]
Apply latest Django security releases (5.0.3, 4.2.11, and 3.2.25): https://www.djangoproject.com/weblog/2024/mar/04/security-releases/

### Open edX services to upgrade

- [x] course-discovery
- [x] credentials
- [x] edx-notes-api
- [x] edx-platform
- [x] enterprise-access
- [x] enterprise-catalog
- [x] license-manager
- [x] xqueue
- [x] xblock-skill-tagging

**Comment by magajh** [comment]
@cmltaWt0: the edx-platform is the only repo still missing the security patch, but I'm updating all the repos with the latest patch to keep everything up to date

**Comment by magajh** [comment]
I wasn't sure if we should include xblock-skill-tagging in this update. If it's not necessary, we can just take it off the task list

**Comment by cmltaWt0** [comment]
> I wasn't sure if we should include xblock-skill-tagging in this update. If it's not necessary, we can just take it off the task list

Since it is installed as a part of edx-platform - I think it's unnecessary.

**Comment by cmltaWt0** [comment]
All patches have been merged.
Thanks @magajh !
