### ISSUE TITLE
[Test failure] TC_LEARNER_8: No login e-mail

### ISSUE THREAD

**Issue by Colin-Fredericks** [openedx/wg-build-test-release#350]
### Release

Redwood

### Expected behavior

When I sign up I should get an e-mail so I can activate my account.

### Actual behavior

I don't.

### Steps to reproduce

1. Go to https://apps.redwood.demo.edly.io/authn/login?next=%2F
2. Sign up. In my case I used the `+` e-mail trick so that I could make multiple throwaway accounts: account+whatever@example.com, account+whatever1@example.com, etc.
3. Wait an hour or so.
4. Check your spam folder.
5. Wait another 2-3 hours.
6. Check again just in case.
7. File a bug report.

Also, I got automatically signed out, which means I couldn't sign back in without activating the account.

<img width="546" alt="Screenshot 2024-05-17 at 1 29 21 PM" src="https://github.com/openedx/wg-build-test-release/assets/1929508/20ec669b-f6c5-49b8-84b2-05f9fb710ffd">
<img width="515" alt="Screenshot 2024-05-17 at 1 29 30 PM" src="https://github.com/openedx/wg-build-test-release/assets/1929508/2ca784bb-a342-45df-be37-ba3bc36a6226">

In the second screenshot I added an arrow pointing toward what I believe to be a related issue, the statement "We just sent an activation link to ." Full stop. That's the end of the sentence.

### Additional information

Yes my username is `b1ff` why do you ask?

**Comment by mariajgrimaldi** [comment]
Hello @Colin-Fredericks, thanks for the report! We'll be looking into it to resolve it as soon as possible.

@DawoudSheraz: could you help us check whether the email configurations for the sandbox are correct and whether emails are being sent?

The sandbox is resetting, so I'll test this again later today.

**Comment by mariajgrimaldi** [comment]
Comment for the last BTR meeting:

Given the sandbox configuration, self-hosted emails do not work. So we recommend using @gmail or any other provider to test these configurations.

Also, we added that in the test sheet getting started tab: https://docs.google.com/spreadsheets/d/1oIU8az2oq-_Dunh4jxhA0OVvcABUinRVRZUgVq4b2IA/edit#gid=1955774185&range=A13, with a recommendation of using the student or admin account for this kind of tests.

**Comment by mariajgrimaldi** [comment]
[Here's](https://openedx.slack.com/archives/C049JQZFR5E/p1716298199246939) an update on the email sending issue:

> FYI we are facing issues with email sending on the redwood sandbox instance; we have opened a ticket on AWS to allow outbound traffic on port 25.

So, we're waiting for a resolution. Thanks for the patience!

**Comment by mariajgrimaldi** [comment]
It's supposed to be fixed now. I registered, but I'm still waiting for my confirmation email. @Colin-Fredericks: could you test again too? Thanks!

**Comment by OmarIthawi** [comment]
My colleagues are reporting the email's still not being received.

**Comment by mariajgrimaldi** [comment]
Yes, it's still happening. I already reported it here: https://openedx.slack.com/archives/C049JQZFR5E/p1716585319047969?thread_ts=1716298199.246939&cid=C049JQZFR5E

Thank you folks.

**Comment by mariajgrimaldi** [comment]
Here's more context on the issue: https://openedx.slack.com/archives/C049JQZFR5E/p1716298199246939

To sum up, email accounts from service providers like Gmail, Hotmail, Yahoo, etc. won't work. If you have a self-hosted email account, it'll probably work. I asked one of my colleagues who uses Protonmail to register and reset their password; they received both emails.

![image](https://github.com/openedx/wg-build-test-release/assets/64440265/4ef80d80-ed80-4d13-9d77-5137c1ece25d)

I'll update the testing instructions for this test and others that rely on email sending. But for the time being, I'll close this issue. Thanks!
