### ISSUE TITLE
[Studio>Course>Section Duplicate] [TC_AUTHOR_26] - Staff user is unable to duplicate a section. 

### ISSUE THREAD

**Issue by FaizanYaqoob617** [openedx/wg-build-test-release#353]
### Release

Redwood

### Expected behavior

Staff user should be able to duplicate a section. 

### Actual behavior

Staff user is unable to duplicate section and the **API** is throwing 500 internal server error. 

### Steps to reproduce

1. Navigate to [**Studio Home** ](https://apps.redwood.demo.edly.io/course-authoring/home) and login with valid credentials of staff user
2. Open any existing course 
3. Click **three dot** icon next to section title
4. Now, click **Duplicate** from expanded options
5. Observe the behavior

**Video Reference:** 

https://github.com/openedx/wg-build-test-release/assets/170403914/77f8e4c8-dcce-44c5-ae3b-f98acca50cb6

**Comment by FaizanYaqoob617** [comment]
label: redwood release testing

**Comment by mariajgrimaldi** [comment]
Thanks for the report! I tested again in the sandbox but can't replicate the issue. 

![Screenshot from 2024-05-22 23-31-29](https://github.com/openedx/wg-build-test-release/assets/64440265/a46ad8fc-468a-41ba-af98-d227cd99dd63)

Could you test again, please?

**Comment by FaizanYaqoob617** [comment]
Hi @mariajgrimaldi 
I retested it, but this time I was unable to reproduce the highlighted issue. It's working perfectly now. ✅

<img width="1780" alt="Section duplication" src="https://github.com/openedx/wg-build-test-release/assets/170403914/b130ee65-971c-4ad7-8523-a81b894d8c10">

**Comment by mariajgrimaldi** [comment]
Great news! I'll be closing this now. Thanks!
