### ISSUE TITLE
[Studio>Course>Subsection Duplicate] [TC_AUTHOR_27] - Staff user is unable to duplicate a subsection. 

### ISSUE THREAD

**Issue by FaizanYaqoob617** [openedx/wg-build-test-release#354]
### Release

Redwood

### Expected behavior

Staff user should be able to duplicate a subsection.

### Actual behavior

Staff user is unable to duplicate subsection and the **API** is throwing 500 internal server error.

### Steps to reproduce

1. Navigate to [**Studio Home** ](https://apps.redwood.demo.edly.io/course-authoring/home)and login with valid credentials of staff user
2. Open any existing course
3. Expand a section and click three dot icon next to **subsection** title
5. Now, click **Duplicate** from expanded options
6. Observe the behavior

**Video Reference:**

https://github.com/openedx/wg-build-test-release/assets/170403914/e3bb2c35-c04f-4a37-84da-b4634dfafc94

**Comment by FaizanYaqoob617** [comment]
label: release testing

**Comment by mariajgrimaldi** [comment]
Thanks for the report! I tested again in the sandbox, but I can't replicate the issue. 
![image](https://github.com/openedx/wg-build-test-release/assets/64440265/b39980d3-594e-4f89-b268-977c6e4e943f)

Could you test again, please?

**Comment by FaizanYaqoob617** [comment]
Hi @mariajgrimaldi 
I retested it, but this time I was unable to reproduce the highlighted issue. It's working perfectly now. ✅ 

<img width="1780" alt="Subsection duplication" src="https://github.com/openedx/wg-build-test-release/assets/170403914/8d1ff685-b7ad-44e8-bc69-5b2dc8c0b7ad">

**Comment by mariajgrimaldi** [comment]
Great news! I'll be closing this now. Thanks!
