### ISSUE TITLE
[Test failure] <TC_AUTHOR_REDWOOD_3>: <Reports are keep loading>

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/wg-build-test-release#356]
### Release

Redwood

### Expected behavior

There should be any data on the page without any errors.

### Actual behavior

Page keeps loading and some of the requests are failing with status code 400.

### Steps to reproduce

1. Go to any course with staff user access
2. go to instructor's tab and click on reports
3. check if reports are showing

label: redwood release testing

### Additional information

Link: https://redwood.demo.edly.io/courses/course-v1:Edly+ed100+1001/instructor#view-aspects
Error message : 	"Error: Error HTTPConnectionPool(host='clickhouse', port=8123): Max retries exceeded with url: /?wait_end_of_query=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x700e9ffca5c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')) executing HTTP request attempt 1 http://clickhouse:8123"

label: redwood release testing

<img width="1440" alt="Screenshot 2024-05-22 at 11 25 34 AM" src="https://github.com/openedx/wg-build-test-release/assets/55684124/ad94d209-4ff8-4fb5-a2af-15ffa24eed05">

**Comment by fayyazahmed66** [comment]
label: redwood release testing

**Comment by mariajgrimaldi** [comment]
Thanks for the report! It looks like we're having some issues with Aspects in the redwood sandbox. I already reported it, I'll report back once I know more.

**Comment by mariajgrimaldi** [comment]
@fayyazahmed66 this is working now. Could you test again? Thanks!

**Comment by fayyazahmed66** [comment]
@mariajgrimaldi  yes its working fine now. We can close this issue. Thanks
