### ISSUE TITLE
[Test failure] <TC_INSTRUCTOR_9>: <Update grades > validation issue>

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/wg-build-test-release#357]
### Release

Redwood

### Expected behavior

There should be a validation check that value should not be greater than 100% and it should show updated value.

### Actual behavior

Incorrect value and validation is missing

### Steps to reproduce

1. Go to instructor's tab of a course with staff access
2. Go to student admin tab
3. click on view gradebook button
4. update student's grade to 99 and check if its updated correctly.

### Additional information

<img width="1440" alt="Screenshot 2024-05-22 at 1 19 02 PM" src="https://github.com/openedx/wg-build-test-release/assets/55684124/1409e5c7-0a18-4622-b119-057aa1221f9d">
<img width="1440" alt="Screenshot 2024-05-22 at 1 19 15 PM" src="https://github.com/openedx/wg-build-test-release/assets/55684124/02e5caad-c102-4da1-912d-8fbdad1cf00b">
<img width="1440" alt="Screenshot 2024-05-22 at 1 21 37 PM" src="https://github.com/openedx/wg-build-test-release/assets/55684124/91b40218-a032-40f5-9cf4-55c98c601bc1">

**Comment by fayyazahmed66** [comment]
label: redwood release testing

**Comment by mariajgrimaldi** [comment]
Thanks for the report! I tested again in the sandbox and can confirm that this is happening. I'll open a new issue in the grade book MFE.

**Comment by mariajgrimaldi** [comment]
In the meantime, I'll test this in a quiet environment to confirm whether it is a regression.
