### ISSUE TITLE
[Test failure] <TC_AUTHOR_REDWOOD_17>: Filtering by "locked" in Studio -> Files doesn't work

### ISSUE THREAD

**Issue by mariiamoskalenko** [openedx/wg-build-test-release#359]
### Release

Redwood

### Expected behavior

As a user, I want to see the file I uploaded and marked as "locked" in the list of files I filtered by "locked" option so that I can operate with all locked files immediately

### Actual behavior

As a user, I don't see the file I uploaded and marked as "locked" in the list of files I filtered by "locked" option so I feel confused and I have to operate with uploaded locked files after the page reloads or separately from other files

https://github.com/openedx/wg-build-test-release/assets/91068576/3d3eb6ca-8f99-46d8-854f-588077892543

### Steps to reproduce

1. The user is on the page Files in Studio.
2. The user uploads the file and marks it "locked" in the file settings.
3. The user chooses the Sort and Filter option.
4. The user chooses the filter by "locked" and applies the filter.
**5. The user DOESN'T see the file he uploaded and marked it as "locked" in the list of filtered files.**

### Additional information

The user can see locked files after the page reloads.

**Comment by mariajgrimaldi** [comment]
Thanks for the report! I tested again in the sandbox and can confirm that this is happening. I'll open a new issue in the course-authoring MFE.

**Comment by GlugovGrGlib** [comment]
The fix was backported into Redwood branch and should be retested after the next Redwood sandbox update.

**Comment by mariajgrimaldi** [comment]
@GlugovGrGlib thank you! I'll close the issue once we test the changes in the sandbox.

**Comment by mariajgrimaldi** [comment]
I tested this in the redwood sanbox and can confirm it's working! Thank you so much folks.
