### ISSUE TITLE
[Test failure] TC_AUTHOR_REDWOOD_1: Operator dashboard not appearing

### ISSUE THREAD

**Issue by alexjmpb** [openedx/wg-build-test-release#360]
### Release

Redwood

### Expected behavior

"Scenario: Superuser can open and view Reports tab with an Operator Dashboard from Instructor Dashboard
Given I am a superuser
When I navigate to the Instructor Dashboard
Then I see a tab labeled Reports
And when I click on the tab
Then I see a Course Dashboard, Individual Learner Reports Link, and an At-Risk Learner Group Reports link, and an Operator Dashboard that I can open and view in the LMS"

### Actual behavior

Only the Course Dashboard, Individual Learner Reports Link, and an At-Risk Learner Group Reports link appear, additionally none of these are loading, appearing multiple 400 responses.

### Steps to reproduce

Login as admin, Go to a course instructors dashboard and go to the reports tab. The content should not be loading.

### Additional information

![image](https://github.com/openedx/wg-build-test-release/assets/62396424/93c1b969-d6ef-43ec-b122-bf8b3a7251bf)

**Comment by mariajgrimaldi** [comment]
Thanks for the report, Alex! It looks like we're having some issues with Aspects in the redwood sandbox. I already reported it, I'll report back once I know more.

**Comment by mariajgrimaldi** [comment]
@alexjmpb: this is working now. Could you test again? Thanks!
