### ISSUE TITLE
[Test failure] TC_AUTHOR_REDWOOD_2: Course dashboard not loading.

### ISSUE THREAD

**Issue by alexjmpb** [openedx/wg-build-test-release#361]
### Release

Redwood

### Expected behavior

"Scenario: Superuser can view Course Dashboard for any course on their instance
Given I am a Superuser viewing the Course Dashboard, the Individual Learner Reports, and the At-Risk Learner Reports
When I click on the Course Name or Course Run input fields in the filter panel on the lefthand side of the Dashboards
Then I see a list of all the Courses (or Course Runs) available on my instance
And when I click on a Course Name and/or a Course Run and the Apply filters button
Then I see a Course Dashboard for the selected Course Name and/or Course Run"

### Actual behavior

The course dashboard does not load. It keeps loading and getting 400 responses.

### Steps to reproduce

Login as admin, Go to a course instructors dashboard and go to the reports tab. The content should not be loading.

### Additional information

![image](https://github.com/openedx/wg-build-test-release/assets/62396424/93c1b969-d6ef-43ec-b122-bf8b3a7251bf)

**Comment by mariajgrimaldi** [comment]
Same comment as in this other issue: https://github.com/openedx/wg-build-test-release/issues/360#issuecomment-2126153875

**Comment by mariajgrimaldi** [comment]
@alexjmpb: this is working now. Could you test again? Thanks!
