### ISSUE TITLE
[Test failure] TC_AUTHOR_121: The grace period cannot be set to less than 1 hour.

### ISSUE THREAD

**Issue by BryanttV** [openedx/wg-build-test-release#365]
### Release

Redwood

### Expected behavior

As a course author, I want to set a grace period at the course level so students can submit assignments after their due date.

### Actual behavior

As a course author, I cannot set a grace period of less than one hour, because the value I type is automatically deleted, even if the format is correct.

### Steps to reproduce

1. From Studio go to **Settings** > **Grading**
2. On the **Grading** page, under **Grading Rules & Policies**, enter a value in the **Grace Period on Deadline** field.
3. Try typing for example: `00:30`. The value will be deleted automatically.

https://github.com/openedx/wg-build-test-release/assets/64033729/c79b518f-4742-48eb-84bf-09a719a98740

### Additional information

The functionality works correctly by setting a value equal to or greater than 1 hour.

**Comment by mariajgrimaldi** [comment]
Thanks for the report! I opened an issue in the course authoring MFE for maintainers to review.

**Comment by mariajgrimaldi** [comment]
I created a backport for the Redwood branch; I hope it gets merged early this week. Thanks!

**Comment by mariajgrimaldi** [comment]
Backport merged! I'll close this issue once we test it in the redwood sandbox.
