### ISSUE TITLE
[Test failure] NO_TEST_ID: It is not possible to update the due dates of the subsections

### ISSUE THREAD

**Issue by BryanttV** [openedx/wg-build-test-release#366]
### Release

Redwood

### Expected behavior

As a course author, I want to update the due dates for the subsections in the course.

### Actual behavior

As a course author, I cannot update the due dates for the subsections in the course. The original date is still assigned.

### Steps to reproduce

1. From **Studio** create a subsection
2. Configure it by assigning it an **assignment type** for the grading and a **due date**.
3. From the LMS, verify that the date is assigned.
4. Update the due date of the subsection.
5. From the LMS the date is not updated. It is still the previous date.

https://github.com/openedx/wg-build-test-release/assets/64033729/08463d88-b317-48a3-abbb-8ed4152dac66

**Comment by mariajgrimaldi** [comment]
So here's what I've found after playing around with subsection dates:
- If you change the date and wait a few minutes, let's say 5, the date will be updated.
- This also happens in quince. I tested it here in case you want to replicate it: https://apps.sandbox.openedx.edly.io/learning/course/course-v1:edX+DemoX+Demo_Course/home
You can use username: admin pass: admin credentials.
Could you test again considering this? Thanks!

**Comment by BryanttV** [comment]
Hi @mariajgrimaldi, I tested as you told me, and you are right.  The changes are reflected about 5 min later.

I wonder if this is the expected behavior.

**Comment by mariajgrimaldi** [comment]
I have a hypothesis for this behavior; I'll ask around to verify it. Given the current system design, though, I do think it's correct.

**Comment by mariajgrimaldi** [comment]
@ormsbee: is this time delay related to how MongoDB - learning sequences updates/synchronization work?

**Comment by ormsbee** [comment]
It seems unlikely to be related to MongoDB if other changes to the outline are showing up properly. It might be the result of caching in [edx-when](https://github.com/openedx/edx-when)?

**Comment by mariajgrimaldi** [comment]
@ormsbee: I also tried updating subsection names, and it takes a bit of time, too, but it's difficult to say if the delay is related.

**Comment by mariajgrimaldi** [comment]
I'm closing this since this is not classified as a bug.
