### ISSUE TITLE
[Test failure] <TC_AUTHOR_REDWOOD_6>: <Name, Username and Emails are not showing in the list>

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/wg-build-test-release#367]
### Release

Redwood

### Expected behavior

Name, Username and Emails should not be empty

### Actual behavior

Name, Username, and Emails column are empty. 

### Steps to reproduce

1. Go to the reports tab under the instructor tab.
2. Click on Individual Learner Dashboard
3. Check learner's summary report 

<img width="1440" alt="Screenshot 2024-05-28 at 2 26 03 PM" src="https://github.com/openedx/wg-build-test-release/assets/55684124/5f9b36a9-2528-453f-927f-e0ee230c6620">

### Additional information

https://redwood.demo.edly.io/courses/course-v1:OpenedX+DemoX+DemoCourse/instructor#view-course_info

**Comment by fayyazahmed66** [comment]
label: redwood release testing

**Comment by DonatoBD** [comment]
Hi @fayyazahmed66 thanks for the report ! I'm a bit lost on aspects but I have the perfect person who can help us understand what's going on 😊

@Ian2012  can you give us a hand here please?

**Comment by Ian2012** [comment]
Hi @fayyazahmed66, this could be because the user pii data has not been enabled. Is the flag `ASPECTS_ENABLE_USER_PII` enabled on the `config.yml`?

If not, I will need access to the instance

**Comment by mariajgrimaldi** [comment]
I asked [here](https://openedx.slack.com/archives/C06AMDA6CAZ/p1717082957959119) for some support. Thank you both!

**Comment by mariajgrimaldi** [comment]
I can see the user's info in the report now, so I'll close this issue. Thank you folks for the assistance!
