### ISSUE TITLE
[TC_LEARNER_17] > Enabling the bulk email from the Django Admin panel doesn't work

### ISSUE THREAD

**Issue by linabashayreh** [openedx/wg-build-test-release#369]
Steps to reproduce:

1- Navigate to https://redwood.demo.edly.io/admin/bulk_email/bulkemailflag/
2- Enable the Bulk email Flag
3- Navigate to the user dashboard
4- Check the course gear icon 

Expected result:
The Email icon should be displayed for the course

Actual Result: 

The Email option is not displayed 

Screenshot 

![2024-05-28_12-49-54](https://github.com/openedx/wg-build-test-release/assets/170809222/38a93b3b-c0e6-4856-8329-c729ed4be2a0)
![image](https://github.com/openedx/wg-build-test-release/assets/170809222/f2f06688-0a35-433c-96e3-31eacd06d611)

**Comment by DonatoBD** [comment]
Hi @linabashayreh Thanks for the report ! I already reviewed the test sheet and found that we need to enable the flag without requiring email authentication

I made that change

![bulk-email-flag](https://github.com/openedx/wg-build-test-release/assets/77167078/8c6007bd-8c41-42e8-959d-99ae62d134a6)

And now the email option appears for me

![learner-dashboard](https://github.com/openedx/wg-build-test-release/assets/77167078/ef12cc49-1e49-4929-84eb-999823a02ad9)

![email-options](https://github.com/openedx/wg-build-test-release/assets/77167078/520cbcf6-d994-4cce-9c02-9aed8ed0c336)

Could you please check if it works for you as well? 😊

**Comment by linabashayreh** [comment]
Thank you @DonatoBD 
Yes checked from my side and it works

**Comment by mariajgrimaldi** [comment]
Thank you folks. I'll be closing this issue now.
