### ISSUE TITLE
PRs to keep eye on before Redwood.2 

### ISSUE THREAD

**Issue by ghassanmas** [openedx/wg-build-test-release#382]
- [ ]  https://github.com/openedx/cs_comments_service/pull/431
  - [ ] https://github.com/overhangio/tutor-forum/pull/34  Todo after redwood.2

**Comment by magajh** [comment]
the security patches from #383 should also be merged before Redwood.2

**Comment by mariajgrimaldi** [comment]
Here's a [list of PR(s)](https://github.com/search?q=org%3Aopenedx+is%3Apr+is%3Aopen+base%3Aopen-release%2Fredwood.master+&type=pullrequests&p=1) currently open against redwood.master (29/07)

I think we should focus on fixes: https://github.com/search?q=org%3Aopenedx+is%3Apr+is%3Aopen+base%3Aopen-release%2Fredwood.master+fix&type=pullrequests

And then on feats: 
https://github.com/search?q=org%3Aopenedx+is%3Apr+is%3Aopen+base%3Aopen-release%2Fredwood.master+feat&type=pullrequests

@cmltaWt0: I can review those and filter out those we should work on.

**Comment by mariajgrimaldi** [comment]
After reviewing the list of PRs labeled as "fix" I've gathered this comprehensive list of PRs:

1. https://github.com/openedx/edx-platform/pull/35149
2. https://github.com/openedx/frontend-app-learning/pull/1404
3. https://github.com/openedx/frontend-app-course-authoring/pull/1047

The rest of the fixes haven't been merged to master. I'll review edx-platform PR (1) and ping assignees for those on the list with one (2 and 3).

**Comment by magajh** [comment]
Here is another list of PRs to keep and eye on before the release https://github.com/openedx/wg-build-test-release/issues/385

**Comment by mariajgrimaldi** [comment]
I'm gonna close this since redwood.2 was already released.
