### ISSUE TITLE
Apply latest Django security patch (4.2.14) for Redwood

### ISSUE THREAD

**Issue by magajh** [openedx/wg-build-test-release#383]
Apply latest Django security release 4.2.14: https://www.djangoproject.com/weblog/2024/jul/09/security-releases/

### Open edX services to upgrade

- [x] course-discovery
- [x] credentials
- [x] edx-notes-api
- [x] edx-platform
- [x] enterprise-access
- [x] enterprise-catalog
- [x] [event-bus-redis](https://github.com/openedx/event-bus-redis)
- [x] license-manager
- [x] [platform-plugin-aspects](https://github.com/openedx/platform-plugin-aspects)
- [x] xqueue

Apply latest Django 3.2.x security patch:
- [x] [openedx-translations](https://github.com/openedx/openedx-translations)

**Comment by cmltaWt0** [comment]
All PRs have being merged. We can close the issue.
