### ISSUE TITLE
Redwood.2 testing

### ISSUE THREAD

**Issue by cmltaWt0** [openedx/wg-build-test-release#384]
### Changes we want to focus on during the testing:

- [ ] https://github.com/openedx/frontend-app-course-authoring/pull/1174
- [ ] https://github.com/openedx/edx-platform/pull/35180
- [ ] https://github.com/openedx/edx-platform/pull/35010

---
We will post any finding regarding the testing in the comments.

**Comment by mariajgrimaldi** [comment]
@cmltaWt0: I merged [this](https://github.com/openedx/edx-platform/pull/35149) minor fix after testing it locally. I don't think it needs further testing, but I'm cross posting it here for future reference :)

**Comment by mariajgrimaldi** [comment]
I'm gonna close this since redwood.2 was already released.
