### ISSUE TITLE
Apply Django Security Patch 4.2.15 Redwood

### ISSUE THREAD

**Issue by magajh** [openedx/wg-build-test-release#385]
Apply latest Django security release 4.2.15: https://www.djangoproject.com/weblog/2024/aug/06/security-releases/

### Open edX services to upgrade

- [x] course-discovery
- [x] credentials
- [x] edx-notes-api
- [x] edx-platform
- [x] enterprise-access
- [x] enterprise-catalog
- [x] [event-bus-redis](https://github.com/openedx/event-bus-redis)
- [x] license-manager
- [x] [platform-plugin-aspects](https://github.com/openedx/platform-plugin-aspects)
- [x] xqueue

**Comment by kdmccormick** [comment]
Thanks @magajh . I am running a routine requirements upgrade for edx-platform, so I will ensure that this patch gets applied to edx-platform master.

**Comment by kdmccormick** [comment]
Done on edx-platform master: https://github.com/openedx/edx-platform/pull/35241

**Comment by cmltaWt0** [comment]
All the patches have been merged. The issue can be closed.
