### ISSUE TITLE
Tests review

### ISSUE THREAD

**Issue by jalondonot** [openedx/wg-build-test-release#390]
**Context**
https://openedx.atlassian.net/wiki/spaces/COMM/pages/4318527513/Redwood.1+Retrospective

**Tasks**
- Remove ones that are no longer relevant. 
- Write better test descriptions for legacy tests, in the style of the new Redwood tests. 
- Look for opportunities to automate tests.

**Comment by pdpinch** [comment]
@angonz and I reviewed the tests in the [Redwood test sheet](https://docs.google.com/spreadsheets/d/1oIU8az2oq-_Dunh4jxhA0OVvcABUinRVRZUgVq4b2IA/edit?gid=0#gid=0) and removed a few in the [Sumac test sheet](https://docs.google.com/spreadsheets/d/1HjmCUAkpe74rQAYM9dllmNy3RKnr70szyhO2rhnhFp0/edit?gid=0#gid=0) that were no longer relevant (e.g. testing waffle flags that have been removed). 

This will need to be a regular process for each release.
