### ISSUE TITLE
[Test failure] <TC_LEARNER_6D>: <HELP LINK NO REDIRECT>

### ISSUE THREAD

**Issue by jciasenza** [openedx/wg-build-test-release#401]
### Release

Sumac

### Expected behavior

Help link on the upper righthand corner that when clicked takes me to the docs site

### Actual behavior

When you click on Help it does not redirect to docs, the page is refreshed
[25.10.2024 13_07.webm](https://github.com/user-attachments/assets/3c588a2a-97ed-44d1-89c0-93686fc59db4)

### Steps to reproduce

. Log in and go to the Discover section.
. Enter the dashboard.
. Click in Help button

**Comment by crathbun428** [comment]
@mariajgrimaldi - It turns out, this is a forked header, this is an issue with the indigo theme, not the software itself. I'm going to removed any header tests from the testing sheet since these tests (it turns out) are testing the theme, and not the software itself.

**Comment by crathbun428** [comment]
@mariajgrimaldi - It turns out this is a forked theme. I would assume this means there are no issues with the release itself, but with the theme instead.

**Comment by crathbun428** [comment]
@mariajgrimaldi - I confirmed that the theme has been updated to include pluggable header slots (this may or may not be super relevant), but the issue does persist in the indigo theme. I believe the issue here is with the Indigo theme.

**Comment by mariajgrimaldi** [comment]
Thank you, @crathbun428! @magajh is working on this, so maybe she can confirm whether it's the indigo theme or a misconfiguration issue.

**Comment by crathbun428** [comment]
Awesome thank you!

**Comment by magajh** [comment]
@crathbun428 thank you! It seems the issue was that the `SUPPORT_URL` site configuration was missing. I have added it here: https://sumac.demo.edly.io/admin/site_configuration/siteconfiguration/1/change/

With this change, the Help link on https://apps.sumac.demo.edly.io/learner-dashboard/ now redirects to https://edx.readthedocs.io/projects/open-edx-learner-guide/en/latest/.

**Comment by jciasenza** [comment]
Thanks, solved!!! 
[Video Screen1733326026533.webm](https://github.com/user-attachments/assets/c2b9f949-4fe7-421d-97fb-383a715ffe99)
