### ISSUE TITLE
[TC_AUTHOR_REDWOOD_69] System does not display the correct results based on the selected filters

### ISSUE THREAD

**Issue by hamzasohail445** [openedx/wg-build-test-release#403]
**Issue # 1**

**Steps to Reproduce:**
1. Go to the Studio home page
2. Select the 'Archived' option and enter the active course name in the search bar field 

Expected Result: System should display archive courses based on the filters and search term. If no results are found, it should display the message: 'We could not find any results'

Actual Result: System displays active courses in the list, not archived ones

**Issue # 2**

**Steps to Reproduce:**
1. Go to the Studio home page
2. Select the 'Archived' option and enter the active course name in the search bar field 
3. Then, clear the search term in the search field.

Expected Result: System should display all archived courses. If no archived courses are found, it should display the message: 'We could not find any results'

Actual Result: System displays all active courses instead of archived courses.

Note:  I have attached the videos for reference.

https://github.com/user-attachments/assets/1c9bdb44-7e5a-4fba-9bb9-13737e37b8fe

https://github.com/user-attachments/assets/60dca24f-c57a-443b-baff-88477cb716ba

**Comment by mariajgrimaldi** [comment]
Thanks for the report! I confirm this is currently happening in the Sumac sandbox. When selecting active/archived and then filtering within those lists, the previous filters on the course status are not being applied. I'll be opening an issue in the corresponding repository.

**Comment by hamzasohail445** [comment]
Hi @mariajgrimaldi , any updates on this issue?

**Comment by mariajgrimaldi** [comment]
@hamzasohail445: a fix was merged early this week! Although I'm not sure it was deployed. Let me check.

**Comment by mariajgrimaldi** [comment]
@hamzasohail445: I think it was. Can you help us test again? Thank you!

**Comment by mariajgrimaldi** [comment]
I followed the steps to reproduce in the community sandbox and now it's working as expected. I'll close this now, considering that it was solved. Thank you!

**Comment by hamzasohail445** [comment]
sorry @mariajgrimaldi for the delayed response. I have already verified this in the sandbox environment and closed the test case in the SUMAC Test Sheet. Everything looks good from my side, please proceed with closing this ticket.
