### ISSUE TITLE
[Test failure] <TC_AUTHOR_141>: <no signatures shown on certificate>

### ISSUE THREAD

**Issue by AntonellaPerrupato** [openedx/wg-build-test-release#407]
### Release

Sumac

### Expected behavior

when you upload the signatures on the certificate, they should be shown

### Actual behavior

Signatures aren't shown: https://sumac.demo.edly.io/certificates/course/course-v1:OpenedX+1+11-2024-1?preview=honor 

### Steps to reproduce

go to a course, previwe certificate

**Comment by mariajgrimaldi** [comment]
Duplicate of https://github.com/openedx/wg-build-test-release/issues/364

**Comment by AntonellaPerrupato** [comment]
@mariajgrimaldi I have checked this, and signatures ares shown in the certificated page, but not in the previsualization. This is how is its supposed to work if you don't modofy the template. 
I'll close this ticket

**Comment by mariajgrimaldi** [comment]
@AntonellaPerrupato: According to this issue, https://github.com/openedx/wg-build-test-release/issues/364, this was a bug. Can you quote where the docs say that's the usual behavior? Then we can share it there and close it as well. Thank you!

**Comment by AntonellaPerrupato** [comment]
@mariajgrimaldi the bug in that ticket refers to signatures don't displaying when you upload them, which is correct, as signatures should be shown. 

What I was trying to say that by default signatures are not shown **in the certificate previuw** if you don't add a html template. 

I think that, images are not shown because the html hasn't been configured in the test environment

https://discuss.openedx.org/t/certificates-no-images-like-signature-or-logos-are-showing-up-on-generated-certificates-does-not-fit-on-regular-a4-paper-etc/9891

https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/latest/set_up_course/studio_add_course_information/studio_creating_certificates.html#setting-up-certificates

https://docs.openedx.org/en/latest/educators/how-tos/set_up_course/create_certificates.html

https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/enable_certificates.html#enable-certificates
