### ISSUE TITLE
[Test failure] <TC_AUTHOR_116>: <YouTube URL for course intro video is not saved>

### ISSUE THREAD

**Issue by AntonellaPerrupato** [openedx/wg-build-test-release#408]
### Release

Sumac

### Expected behavior

YouTube URL for course intro video should be saved and shown

### Actual behavior

YouTube URL for course intro video is not saved and not shown

### Steps to reproduce

https://apps.sumac.demo.edly.io/authoring/course/course-v1:OpenedX+1+11-2024/settings/details

add a url: https://www.youtube.com/watch?v=GkEserKBnWc

**Comment by mariajgrimaldi** [comment]
Thank you for the report! I can use an introductory YouTube video, so this is technically not a bug. However, I can't see the play button on the course about page, making it difficult to see if there's a video for the course. If you click on the course image, then you can watch the video:

[Screencast from 18-11-24 17:14:04.webm](https://github.com/user-attachments/assets/c0138038-24cb-44df-bba0-bfc28b3257e9)

I tested this also in my local environment with the Open edX default theme, and I can see the play button:

![image](https://github.com/user-attachments/assets/41048b0c-0ad0-46dd-a3fb-b69d990cfe0e)

So this is probably related to the indigo theme.

**Comment by mariajgrimaldi** [comment]
The tutor-indigo maintainers are currently working on this :)
