### ISSUE TITLE
[Tutor] Document migration from native installation

### ISSUE THREAD

**Issue by arbrandes** [openedx/wg-build-test-release#78]
As described in [Criterion 6](https://github.com/edx/open-edx-proposals/blob/master/oeps/oep-0045/decisions/0001-tutor-as-replacement-for-edx-configuration.rst#criterion-6-migration-from-the-native-installation) of OEP-45, ADR-1, the community needs a documented way to migrate from the now deprecated [native installation](https://openedx.atlassian.net/wiki/spaces/OpenOPS/pages/1969455764/Koa+Native+Open+edX+platform+Ubuntu+20.04+64+bit+Installation) into a Tutor-deployed one.

Given the current timeframe, this documentation should target a migration from edx/configuration@lilac.X to tutor@maple.1.

**Comment by regisb** [comment]
One Tutor user already made a lot of research on this particular topic: https://discuss.overhang.io/t/migrating-from-native-install-to-tutor-juniper-tutor-10-x/1533

**Comment by regisb** [comment]
@BbrSofiane did you make progress on this?

**Comment by BbrSofiane** [comment]
@regisb I have a set of notes that I need to clean up and write somewhere. This shouldn't take me more than a couple of hours.

**Comment by regisb** [comment]
> This shouldn't take me more than a couple of hours.

Famous last words

:wink:  No but seriously, I'm glad that you tackled this.

**Comment by BbrSofiane** [comment]
> Famous last words

Indeed 😂

**Comment by BbrSofiane** [comment]
https://openedx.atlassian.net/wiki/spaces/COMM/pages/3249438723/Migration+from+native+to+tutor

**Comment by NeOneSoft** [comment]
Hello @BbrSofiane, do you consider that we need to document more details about this process?Thank you so much

**Comment by BbrSofiane** [comment]
@NeOneSoft I think the document provides a good starting point. Going forward it can be improved based on feedback from people using it. I'm happy to close the issue unless there are additional comments,

**Comment by NeOneSoft** [comment]
@BbrSofiane thank you so much for you response!!. If you are agree and there's no additional comments you can go ahead. Thanks again!!
